"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";
import { useRouter } from "next/navigation";

type CostLine = { id:string; cost_phase:string|null; description:string; quantity:number; unit:string; amount:number };
type Quotation = { id:string; quotation_ref:string|null; quotation_date:string|null; version_no:number; status:string; total_amount:number; scope_summary:string|null; contractor_legal_name:string|null; gst_treatment:string|null; itemization_note:string|null; approved_at:string|null; approval_note:string|null };
type Rule = { minimum_quotations?:number; maximum_amount?:number };
type Financial = { estimated_cost:number; quoted_cost:number|null; approved_budget:number|null; cost_status:string; financial_approved_at:string|null; rule?:Rule|Rule[] };
type Payment = { id:string; status:string; assessed_amount:number; invoice_reference:string|null; payment_term_started_at:string|null; payment_due_at:string|null; recommendation_note:string|null; approved_at:string|null; completion_notified_at:string|null; paid_amount:number|null; payment_reference:string|null; paid_at:string|null };
type Document = { id:string; document_type:"quotation"|"invoice"; quotation_id:string|null; payment_assessment_id:string|null; original_filename:string; uploaded_at:string };
type Workspace = { costs:CostLine[]; procurement:Array<{id:string;purchase_reference:string;description:string;committed_amount:number;status:string}>; quotations:Quotation[]; financial:Financial|null; contractor:{name?:string;payment_terms_days?:number}|Array<{name?:string;payment_terms_days?:number}>|null; actual_costs_confirmed_at:string|null; order:{title?:string;status?:string;reviewed_at?:string;asset?:{asset_tag?:string;name?:string}|Array<{asset_tag?:string;name?:string}>}|null; payment:Payment|null; documents:Document[]; correction:{id:string;reason:string}|null };

const input="min-h-11 w-full rounded border border-slate-300 bg-white px-3 text-sm";
const money=(value:number|null|undefined)=>value===null||value===undefined?"Pending":`S$${new Intl.NumberFormat("en-SG",{minimumFractionDigits:2,maximumFractionDigits:2}).format(Number(value))}`;
const date=(value:string|null|undefined)=>value?new Intl.DateTimeFormat("en-SG",{dateStyle:"medium"}).format(new Date(value)):"Pending";
const field=(form:FormData,name:string)=>String(form.get(name)??"").trim();

export default function ReleaseOneWorkspace({id,role,status}:{id:string;role:string;status:string}) {
  const router=useRouter();
  const [data,setData]=useState<Workspace|null>(null);
  const [error,setError]=useState<string|null>(null);
  const [message,setMessage]=useState<string|null>(null);
  const [busy,setBusy]=useState(false);
  const [proposalOpen,setProposalOpen]=useState(false);
  const [paymentOpen,setPaymentOpen]=useState(false);
  const load=useCallback(async()=>{const response=await fetch(`/api/work-orders/${id}/release-1`,{cache:"no-store"});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.message??"Commercial workspace unavailable.");const w=body.data??{};setData({costs:Array.isArray(w.costs)?w.costs:[],procurement:Array.isArray(w.procurement)?w.procurement:[],quotations:Array.isArray(w.quotations)?w.quotations:[],financial:w.financial??null,contractor:w.contractor??null,actual_costs_confirmed_at:w.actual_costs_confirmed_at??null,order:w.order??null,payment:w.payment??null,documents:Array.isArray(w.documents)?w.documents:[],correction:w.correction??null});},[id]);
  useEffect(()=>{void load().catch((cause)=>setError(cause instanceof Error?cause.message:"Commercial workspace unavailable."));},[load]);
  async function submit(operation:string,payload:Record<string,unknown>,success:string){setBusy(true);setError(null);setMessage(null);try{const response=await fetch(`/api/work-orders/${id}/release-1`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation,payload})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.message??"Update failed.");await load();router.refresh();setMessage(success);}catch(cause){setError(cause instanceof Error?cause.message:"Update failed.");}finally{setBusy(false);}}
  async function upload(type:"quotation"|"invoice",recordId:string,file:File|null){if(!file){setError("Choose a PDF or image to attach.");return;}setBusy(true);setError(null);setMessage(null);try{const form=new FormData();form.set("document_type",type);form.set("record_id",recordId);form.set("file",file);const response=await fetch(`/api/work-orders/${id}/commercial-documents`,{method:"POST",body:form});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.message??"Attachment failed.");await load();setMessage(type==="quotation"?"Contractor quotation attached.":"Contractor invoice attached.");}catch(cause){setError(cause instanceof Error?cause.message:"Attachment failed.");}finally{setBusy(false);}}
  async function openDocument(documentId:string){const response=await fetch(`/api/work-orders/${id}/commercial-documents/${documentId}/access`,{method:"POST"});const body=await response.json();if(!response.ok||!body.ok){setError(body.message??"Document unavailable.");return;}window.open(body.url,"_blank","noopener,noreferrer");}
  async function downloadDocument(documentId:string){setError(null);const response=await fetch(`/api/work-orders/${id}/commercial-documents/${documentId}/access`,{method:"POST"});const body=await response.json();if(!response.ok||!body.ok){setError(body.message??"Document unavailable.");return;}const file=await fetch(body.url);if(!file.ok){setError("Document download failed.");return;}const url=URL.createObjectURL(await file.blob());const anchor=document.createElement("a");anchor.href=url;anchor.download=body.filename??"supporting-document";document.body.appendChild(anchor);anchor.click();anchor.remove();URL.revokeObjectURL(url);}

  const technician=role==="technician";
  const approver=["approver","supervisor","facility_manager","administrator"].includes(role);
  const actual=useMemo(()=>data?.costs.filter((line)=>line.cost_phase==="actual").reduce((sum,line)=>sum+Number(line.amount),0)??0,[data]);
  const quote=data?.quotations[0]??null;
  const contractor=Array.isArray(data?.contractor)?data?.contractor[0]:data?.contractor;
  const asset=Array.isArray(data?.order?.asset)?data?.order?.asset[0]:data?.order?.asset;
  const rule=Array.isArray(data?.financial?.rule)?data?.financial?.rule[0]:data?.financial?.rule;
  const baseline=data?.financial?.approved_budget??data?.financial?.quoted_cost??quote?.total_amount??null;
  const quoteDocs=data?.documents.filter((item)=>item.document_type==="quotation"&&item.quotation_id===quote?.id)??[];
  const approvedQuotes=data?.quotations.filter((item)=>["approved","superseded"].includes(item.status))??[];
  const invoiceDocs=data?.documents.filter((item)=>item.document_type==="invoice"&&item.payment_assessment_id===data.payment?.id)??[];
  const verified=["reviewed","closed"].includes(data?.order?.status??status);
  const saveProposal=(event:FormEvent<HTMLFormElement>)=>{event.preventDefault();const form=new FormData(event.currentTarget);void submit("save_proposal",{scope_summary:field(form,"scope_summary"),proposed_amount:Number(form.get("proposed_amount")),quotation_ref:field(form,"quotation_ref"),quotation_date:field(form,"quotation_date"),contractor_legal_name:field(form,"contractor_legal_name"),itemization_note:field(form,"itemization_note"),gst_treatment:field(form,"gst_treatment")},"Proposal draft saved.");};

  return <section className="border-t border-neutral-200 pt-6" aria-labelledby="cost-summary-heading">
    <div><p className="text-xs font-black uppercase text-emerald-700">Release 1 commercial control</p><h2 id="cost-summary-heading" className="text-xl font-black text-slate-950">Cost Summary</h2><p className="mt-1 text-sm text-slate-600">Proposal, independent approval, final account and Finance payment are separate audited steps.</p></div>
    {error&&<p role="alert" className="mt-3 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}{message&&<p role="status" className="mt-3 rounded border border-emerald-200 bg-emerald-50 p-3 text-sm text-emerald-800">{message}</p>}
    {!data?<p className="mt-4 text-sm text-slate-500">Loading commercial controls...</p>:<>
      <dl className="mt-4 grid gap-px overflow-hidden rounded border bg-slate-200 sm:grid-cols-2 lg:grid-cols-4">{[
        ["Estimated cost",money(data.financial?.estimated_cost)],["Quoted cost",money(data.financial?.quoted_cost??quote?.total_amount)],["Approved amount / budget",money(data.financial?.approved_budget)],["Actual cost",money(actual)],["Variance",money(baseline===null?null:actual-Number(baseline))],["Contractor",contractor?.name??"Assigned record pending"],["Quotation",quote?.quotation_ref?`${quote.quotation_ref} / ${money(quote.total_amount)}`:quote?`${money(quote.total_amount)} / authentic reference pending`:"Not prepared"],["Cost status",(data.financial?.cost_status??"not configured").replaceAll("_"," ")],["Financial approval",data.financial?.financial_approved_at?`Approved ${date(data.financial.financial_approved_at)}`:"Pending independent approval"],["Quotation rule",`${rule?.minimum_quotations??1} quotation required below ${money(rule?.maximum_amount??1000)}`],["Actual costing",data.actual_costs_confirmed_at?`Confirmed / ${money(actual)}`:"Awaiting confirmation"]
      ].map(([label,value])=><div key={label} className="bg-white p-4"><dt className="text-xs font-bold uppercase text-slate-500">{label}</dt><dd className="mt-1 font-bold capitalize text-slate-950">{value}</dd></div>)}</dl>

      <section className="mt-6 border-t border-slate-200 pt-5" aria-labelledby="proposal-heading">
        <Header id="proposal-heading" title="Proposal / Quotation" subtitle={`${asset?.asset_tag??"Asset"} / ${asset?.name??data.order?.title??"Work Order repair"}`} status={quote?.status??"not prepared"}/>
        {quote&&<dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Repair scope" value={quote.scope_summary}/><Info label="Proposed amount" value={money(quote.total_amount)}/><Info label="Quotation reference" value={quote.quotation_ref??"Pending authentic quotation"}/><Info label="Quotation date" value={quote.quotation_date??"Pending authentic quotation"}/><Info label="Contractor legal name" value={quote.contractor_legal_name??"Pending authentic quotation"}/><Info label="Itemized charges" value={quote.itemization_note??"Pending authentic quotation"}/><Info label="GST treatment" value={quote.gst_treatment??"Pending authentic quotation"}/><Info label="Independent approval" value={quote.approved_at?`${date(quote.approved_at)} / ${quote.approval_note}`:"Pending"}/></dl>}
        {technician&&quote&&["approved","superseded"].includes(quote.status)&&data.correction&&<div className="mt-4"><button type="button" disabled={busy} onClick={()=>void submit("start_quotation_revision",{},"Controlled quotation revision opened.")} className="min-h-11 rounded bg-blue-700 px-4 font-bold text-white">Prepare Quotation Revision</button></div>}
        {technician&&quote&&["draft","returned"].includes(quote.status)&&<div className="mt-4"><button type="button" onClick={()=>setProposalOpen((v)=>!v)} className="min-h-11 rounded bg-blue-700 px-4 font-bold text-white">Prepare Proposal</button></div>}
        {technician&&quote&&proposalOpen&&["draft","returned"].includes(quote.status)&&<form onSubmit={saveProposal} className="mt-3 grid gap-3 border-l-4 border-blue-600 bg-slate-50 p-4 sm:grid-cols-2"><Label title="Repair scope" wide><input name="scope_summary" required defaultValue={quote.scope_summary??"Repair and test RS-01 - Loading Bay Roller Shutter No. 1"} className={input}/></Label><Label title="Proposed amount (SGD)"><input name="proposed_amount" required type="number" min="0" step="0.01" defaultValue={quote.total_amount||650} className={input}/></Label><Label title="Quotation reference (optional until received)"><input name="quotation_ref" defaultValue={quote.quotation_ref??""} className={input}/></Label><Label title="Quotation date (optional)"><input name="quotation_date" type="date" defaultValue={quote.quotation_date??""} className={input}/></Label><Label title="Contractor legal name (from authentic quotation)"><input name="contractor_legal_name" defaultValue={quote.contractor_legal_name??""} className={input}/></Label><Label title="Itemized charges (from authentic quotation)" wide><textarea name="itemization_note" defaultValue={quote.itemization_note??""} className="min-h-24 w-full rounded border border-slate-300 bg-white p-3 text-sm"/></Label><Label title="GST treatment (from authentic quotation)"><select name="gst_treatment" defaultValue={quote.gst_treatment??""} className={input}><option value="">Pending authentic quotation</option><option>GST inclusive</option><option>GST exclusive</option><option>No GST stated</option></select></Label><button disabled={busy} className="min-h-11 self-end rounded bg-blue-700 px-4 font-bold text-white">Save Draft</button></form>}
        {technician&&quote&&["draft","returned"].includes(quote.status)&&<UploadForm name="quotation_file" label="Authentic contractor quotation (PDF/image)" button={quoteDocs.length?"Replace Draft Quotation":"Attach Quotation"} busy={busy} onFile={(file)=>upload("quotation",quote.id,file)}/>}<DocumentList documents={quoteDocs} onOpen={openDocument} onDownload={downloadDocument}/>
        {technician&&quote&&["draft","returned"].includes(quote.status)&&<form className="mt-3 flex flex-wrap items-end gap-3" onSubmit={(event)=>{event.preventDefault();void submit("submit_proposal",{quotation_id:quote.id,note:field(new FormData(event.currentTarget),"note")},"Proposal submitted for independent approval.");}}><Label title="Technician recommendation" grow><input name="note" required defaultValue="Recommend the S$650 RS-01 repair proposal under the below-S$1,000 one-quotation rule." className={input}/></Label><button disabled={busy||quoteDocs.length===0} className="min-h-11 rounded bg-blue-700 px-4 font-bold text-white disabled:bg-slate-400">Submit for Approval</button><p className="w-full text-xs text-slate-600">Attach the authentic quotation before submission. Technicians cannot approve their own expenditure.</p></form>}
        {approver&&quote?.status==="submitted"&&<ApprovalForm label="Independent approval note" button="Independent Approval" busy={busy} onSubmit={(note)=>submit("approve_proposal",{quotation_id:quote.id,note},"S$650 proposal independently approved.")}/>}
        {approvedQuotes.length>0&&<div className="mt-5 border-t border-slate-200 pt-4"><h4 className="font-bold">Approved quotation history</h4>{approvedQuotes.map((item)=><article key={item.id} className="mt-3 rounded border bg-slate-50 p-3 text-sm"><div className="flex flex-wrap justify-between gap-2"><strong>Version {item.version_no} / {money(item.total_amount)}</strong><span className="font-bold uppercase text-slate-600">{item.status}</span></div><p className="mt-1">Approved {date(item.approved_at)}. Supporting document is read-only.</p><DocumentList documents={data.documents.filter((document)=>document.document_type==="quotation"&&document.quotation_id===item.id)} onOpen={openDocument} onDownload={downloadDocument}/></article>)}</div>}
      </section>

      <section className="mt-6 border-t border-slate-200 pt-5" aria-labelledby="payment-heading">
        <Header id="payment-heading" title="Contractor Final Account / Payment Proposal" subtitle="Available after verified completion. Approval does not record actual Finance payment." status={data.payment?.status?.replaceAll("_"," ")??(verified?"ready to prepare":"awaiting verified completion")}/>
        {data.payment&&<dl className="mt-3 grid gap-3 text-sm sm:grid-cols-2 lg:grid-cols-4"><Info label="Recommended payment" value={money(data.payment.assessed_amount)}/><Info label="Confirmed actual cost" value={money(actual)}/><Info label="Payment commencement" value={date(data.payment.payment_term_started_at)}/><Info label="30-day due date" value={date(data.payment.payment_due_at)}/><Info label="Invoice reference" value={data.payment.invoice_reference??"Pending authentic invoice"}/><Info label="Completion notification" value={data.payment.completion_notified_at?`Queued ${date(data.payment.completion_notified_at)}`:"Not yet sent"}/><Info label="Payment approval" value={data.payment.approved_at?`Approved ${date(data.payment.approved_at)}`:"Pending independent approval"}/><Info label="Finance payment" value={data.payment.paid_at?`${money(data.payment.paid_amount)} / ${data.payment.payment_reference}`:"Not recorded"}/></dl>}
        {technician&&verified&&data.payment&&["draft","returned"].includes(data.payment.status)&&<div className="mt-4"><button type="button" onClick={()=>setPaymentOpen((v)=>!v)} className="min-h-11 rounded bg-blue-700 px-4 font-bold text-white">Prepare Final Account</button></div>}
        {technician&&paymentOpen&&data.payment&&["draft","returned"].includes(data.payment.status)&&<form className="mt-3 grid gap-3 border-l-4 border-blue-600 bg-slate-50 p-4 sm:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);void submit("save_payment_proposal",{invoice_reference:field(form,"invoice_reference"),recommendation_note:field(form,"recommendation_note")},"Final account draft saved at the confirmed S$620 actual cost.");}}><Label title="Recommended payment (confirmed actual)"><input readOnly value={actual} className={`${input} bg-slate-100`}/></Label><Label title="Invoice reference (optional until received)"><input name="invoice_reference" defaultValue={data.payment.invoice_reference??""} className={input}/></Label><Label title="Recommendation note" wide><textarea name="recommendation_note" required defaultValue={data.payment.recommendation_note??"Recommend payment of the confirmed actual cost after verified completion."} className="min-h-24 w-full rounded border border-slate-300 bg-white p-3 text-sm"/></Label><button disabled={busy} className="min-h-11 rounded bg-blue-700 px-4 font-bold text-white sm:col-span-2">Save Draft</button></form>}
        {technician&&data.payment&&["draft","returned"].includes(data.payment.status)&&<UploadForm name="invoice_file" label="Contractor invoice (PDF/image)" button="Attach Invoice" busy={busy} onFile={(file)=>upload("invoice",data.payment!.id,file)}/>}<DocumentList documents={invoiceDocs} onOpen={openDocument} onDownload={downloadDocument}/>
        {technician&&data.payment&&["draft","returned"].includes(data.payment.status)&&<button type="button" disabled={busy||invoiceDocs.length===0} onClick={()=>void submit("submit_payment_proposal",{note:data.payment?.recommendation_note??"Recommend payment of confirmed actual cost."},"Payment proposal submitted; completion notification queued.")} className="mt-3 min-h-11 rounded bg-blue-700 px-4 font-bold text-white disabled:bg-slate-400">Submit Payment Proposal</button>}
        {approver&&data.payment?.status==="awaiting_approval"&&<ApprovalForm label="Independent payment approval note" button="Independent Payment Approval" busy={busy} onSubmit={(note)=>submit("approve_payment",{note},"S$620 payment independently approved; Finance payment remains unrecorded.")}/>}
        {role==="administrator"&&data.payment?.status==="approved_for_payment"&&<form className="mt-4 grid gap-3 border-l-4 border-slate-600 bg-slate-50 p-4 sm:grid-cols-2" onSubmit={(event)=>{event.preventDefault();const form=new FormData(event.currentTarget);void submit("record_finance_payment",{paid_amount:Number(form.get("paid_amount")),paid_at:field(form,"paid_at"),payment_reference:field(form,"payment_reference"),payment_note:field(form,"payment_note")},"Finance payment recorded separately.");}}><input name="paid_amount" required type="number" min="0" step="0.01" defaultValue={data.payment.assessed_amount} aria-label="Paid amount" className={input}/><input name="paid_at" required type="datetime-local" aria-label="Paid at" className={input}/><input name="payment_reference" required placeholder="Finance payment reference" className={input}/><input name="payment_note" required placeholder="Finance payment note" className={input}/><button disabled={busy} className="min-h-11 rounded bg-slate-800 px-4 font-bold text-white sm:col-span-2">Record Finance Payment</button></form>}
      </section>
      <section className="mt-6 border-t border-slate-200 pt-5"><h3 className="font-bold">Procurement commitments</h3>{data.procurement.length?data.procurement.map((item)=><article key={item.id} className="mt-3 flex flex-wrap justify-between gap-3 rounded border bg-white p-3 text-sm"><div><strong>{item.purchase_reference} / {item.status}</strong><p>{item.description}</p></div><strong>{money(item.committed_amount)}</strong></article>):<p className="mt-2 text-sm text-slate-500">No procurement commitment recorded.</p>}</section>
    </>}
  </section>;
}

function Header({id,title,subtitle,status}:{id:string;title:string;subtitle:string;status:string}){return <div className="flex flex-wrap items-start justify-between gap-3"><div><h3 id={id} className="font-black text-slate-950">{title}</h3><p className="mt-1 text-sm text-slate-600">{subtitle}</p></div><span className="rounded border border-slate-300 bg-white px-2 py-1 text-xs font-bold uppercase">{status}</span></div>;}
function Info({label,value}:{label:string;value:string|null|undefined}){return <div><dt className="font-bold text-slate-500">{label}</dt><dd>{value??"Pending"}</dd></div>;}
function Label({title,wide=false,grow=false,children}:{title:string;wide?:boolean;grow?:boolean;children:React.ReactNode}){return <label className={`text-sm font-bold ${wide?"sm:col-span-2":""} ${grow?"min-w-64 flex-1":""}`}>{title}<span className="mt-1 block">{children}</span></label>;}
function UploadForm({name,label,button,busy,onFile}:{name:string;label:string;button:string;busy:boolean;onFile:(file:File|null)=>void}){return <form className="mt-3 flex flex-wrap items-end gap-3" onSubmit={(event)=>{event.preventDefault();const item=new FormData(event.currentTarget).get(name);onFile(item instanceof File?item:null);}}><Label title={label} grow><input name={name} type="file" accept="application/pdf,image/jpeg,image/png,image/webp" className={`${input} py-2`}/></Label><button disabled={busy} className="min-h-11 rounded border border-blue-700 bg-white px-4 font-bold text-blue-700">{button}</button></form>;}
function ApprovalForm({label,button,busy,onSubmit}:{label:string;button:string;busy:boolean;onSubmit:(note:string)=>Promise<void>}){return <form className="mt-4 flex flex-wrap items-end gap-3 border-l-4 border-emerald-600 bg-emerald-50 p-4" onSubmit={(event)=>{event.preventDefault();void onSubmit(field(new FormData(event.currentTarget),"note"));}}><Label title={label} grow><input name="note" required className={input}/></Label><button disabled={busy} className="min-h-11 rounded bg-emerald-700 px-4 font-bold text-white">{button}</button></form>;}
function DocumentList({documents,onOpen,onDownload}:{documents:Document[];onOpen:(id:string)=>Promise<void>;onDownload:(id:string)=>Promise<void>}){if(!documents.length)return <p className="mt-2 text-sm text-slate-500">No attachment received.</p>;return <ul className="mt-2 space-y-2">{documents.map((document)=><li key={document.id} className="flex flex-wrap items-center justify-between gap-3 rounded border bg-white p-3 text-sm"><span><strong>{document.original_filename}</strong> / attached {date(document.uploaded_at)}</span><span className="flex gap-2"><button type="button" onClick={()=>void onOpen(document.id)} className="min-h-9 rounded border border-slate-400 px-3 font-bold">Open</button><button type="button" onClick={()=>void onDownload(document.id)} className="min-h-9 rounded border border-slate-400 px-3 font-bold">Download</button></span></li>)}</ul>;}
