"use client";

import { useCallback, useEffect, useState } from "react";
import { useRouter } from "next/navigation";

type Workspace = {
  markups: Array<{ id:string; source_type:string; source_reference:string; page_number:number|null; x_percent:number; y_percent:number; note:string }>;
  costs: Array<{ id:string; cost_phase:string|null; cost_type:string; description:string; quantity:number; unit:string; unit_rate:number; amount:number }>;
  procurement: Array<{ id:string; purchase_reference:string; description:string; currency:string; committed_amount:number; status:string }>;
  quotations: Array<Record<string, unknown>>;
  rates: Array<Record<string, unknown>>;
};

export default function ReleaseOneWorkspace({ id, role, status }: { id:string; role:string; status:string }) {
  const router = useRouter();
  const [data,setData]=useState<Workspace|null>(null); const [error,setError]=useState<string|null>(null); const [busy,setBusy]=useState(false);
  const load=useCallback(async()=>{ const response=await fetch(`/api/work-orders/${id}/release-1`,{cache:"no-store"}); const body=await response.json(); if(!response.ok||!body.ok) throw new Error(body.message??"Release 1 workspace unavailable."); const workspace=body.data??{}; setData({markups:Array.isArray(workspace.markups)?workspace.markups:[],costs:Array.isArray(workspace.costs)?workspace.costs:[],procurement:Array.isArray(workspace.procurement)?workspace.procurement:[],quotations:Array.isArray(workspace.quotations)?workspace.quotations:[],rates:Array.isArray(workspace.rates)?workspace.rates:[]}); },[id]);
  useEffect(()=>{void load().catch((cause)=>setError(cause instanceof Error?cause.message:"Release 1 workspace unavailable."));},[load]);
  async function submit(operation:string,payload:Record<string,unknown>){setBusy(true);setError(null);try{const response=await fetch(`/api/work-orders/${id}/release-1`,{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({operation,payload})});const body=await response.json();if(!response.ok||!body.ok)throw new Error(body.message??"Update failed.");await load();router.refresh();}catch(cause){setError(cause instanceof Error?cause.message:"Update failed.");}finally{setBusy(false);}}
  const technician=role==="technician"&&["assigned","in_progress"].includes(status); const manager=["supervisor","facility_manager","administrator"].includes(role);
  return <section className="border-t border-neutral-200 pt-6" aria-labelledby="release-one-heading">
    <h2 id="release-one-heading" className="text-lg font-semibold text-neutral-900">Markup, Cost &amp; Procurement</h2>
    <p className="mt-1 text-sm text-neutral-600">Controlled Work Order records. Visibility does not grant mutation authority.</p>
    {error&&<p role="alert" className="mt-3 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error}</p>}
    {!data?<p className="mt-4 text-sm text-neutral-500">Loading controlled records...</p>:<div className="mt-4 grid gap-5 lg:grid-cols-2">
      <div className="space-y-3"><h3 className="font-bold">Drawing / PDF markup</h3>{data.markups.map(x=><div key={x.id} className="rounded border p-3 text-sm"><strong>{x.source_reference}{x.page_number?` · page ${x.page_number}`:""}</strong><p>{x.note}</p><p className="text-neutral-500">Position {x.x_percent}%, {x.y_percent}%</p></div>)}{data.markups.length===0&&<p className="text-sm text-neutral-500">No markup recorded.</p>}
      {(technician||manager)&&<form className="grid gap-2 rounded border bg-neutral-50 p-3 sm:grid-cols-2" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);void submit("markup",Object.fromEntries(f));}}><select name="source_type" aria-label="Markup source type" className="rounded border p-2"><option value="drawing">Drawing</option><option value="pdf">PDF</option></select><input name="source_reference" required placeholder="Drawing or PDF reference" className="rounded border p-2"/><input name="page_number" type="number" min="1" placeholder="PDF page (optional)" className="rounded border p-2"/><input name="x_percent" required type="number" min="0" max="100" step="0.1" placeholder="X %" className="rounded border p-2"/><input name="y_percent" required type="number" min="0" max="100" step="0.1" placeholder="Y %" className="rounded border p-2"/><input name="note" required placeholder="Markup note" className="rounded border p-2 sm:col-span-2"/><button disabled={busy} className="rounded bg-blue-700 p-2 font-bold text-white sm:col-span-2">Add markup pin</button></form>}</div>
      <div className="space-y-3"><h3 className="font-bold">Actual cost</h3>{data.costs.map(x=><div key={x.id} className="flex justify-between rounded border p-3 text-sm"><span>{x.description} <small>({x.cost_phase??"legacy"})</small></span><strong>S${Number(x.amount).toFixed(2)}</strong></div>)}{data.costs.length===0&&<p className="text-sm text-neutral-500">No structured cost lines.</p>}
      {technician&&<form className="grid gap-2 rounded border bg-neutral-50 p-3 sm:grid-cols-2" onSubmit={(e)=>{e.preventDefault();void submit("actual_cost",Object.fromEntries(new FormData(e.currentTarget)));}}><select name="cost_type" aria-label="Cost type" className="rounded border p-2">{["labour","material","equipment","service","callout"].map(x=><option key={x}>{x}</option>)}</select><input name="description" required placeholder="Description" className="rounded border p-2"/><input name="quantity" required type="number" min="0" step="0.01" placeholder="Quantity" className="rounded border p-2"/><input name="unit" required placeholder="Unit" className="rounded border p-2"/><input name="unit_rate" required type="number" min="0" step="0.01" placeholder="Unit rate (SGD)" className="rounded border p-2"/><input name="worker_name" placeholder="Worker (optional)" className="rounded border p-2"/><button disabled={busy} className="rounded bg-blue-700 p-2 font-bold text-white">Add actual cost</button><button type="button" disabled={busy} onClick={()=>void submit("confirm_actual_costs",{})} className="rounded border border-blue-700 p-2 font-bold text-blue-700">Confirm costing complete</button></form>}</div>
      <div className="space-y-3"><h3 className="font-bold">Quotations</h3>{data.quotations.map((x,i)=><pre key={String(x.id??i)} className="overflow-auto rounded border p-3 text-xs">{JSON.stringify(x,null,2)}</pre>)}{data.quotations.length===0&&<p className="text-sm text-neutral-500">No governed quotation recorded.</p>}
      {manager&&data.rates.length>0&&<form className="grid gap-2 rounded border bg-neutral-50 p-3 sm:grid-cols-2" onSubmit={(e)=>{e.preventDefault();const f=new FormData(e.currentTarget);const rate=data.rates.find((x)=>String(x.id??x.rate_item_id)===String(f.get("rate_item_id")));void submit("quotation",{quotation_ref:f.get("quotation_ref"),quotation_date:f.get("quotation_date"),lines:[{rate_item_id:f.get("rate_item_id"),quantity:Number(f.get("quantity")),quoted_unit_rate:Number(f.get("quoted_unit_rate")),description:String(rate?.description??"Quoted service"),unit:String(rate?.unit??"unit")} ]});}}><input name="quotation_ref" required placeholder="Quotation reference" className="rounded border p-2"/><input name="quotation_date" required type="date" className="rounded border p-2"/><select name="rate_item_id" aria-label="Contractor rate item" className="rounded border p-2 sm:col-span-2">{data.rates.map((x,i)=><option key={String(x.id??x.rate_item_id??i)} value={String(x.id??x.rate_item_id)}>{String(x.item_code??x.description??`Rate item ${i+1}`)}</option>)}</select><input name="quantity" required type="number" min="0" step="0.01" placeholder="Quantity" className="rounded border p-2"/><input name="quoted_unit_rate" required type="number" min="0" step="0.01" placeholder="Quoted unit rate" className="rounded border p-2"/><button disabled={busy} className="rounded bg-blue-700 p-2 font-bold text-white sm:col-span-2">Record quotation revision</button></form>}</div>
      <div className="space-y-3"><h3 className="font-bold">Procurement commitments</h3>{data.procurement.map(x=><div key={x.id} className="rounded border p-3 text-sm"><strong>{x.purchase_reference} · {x.status}</strong><p>{x.description}</p><p>{x.currency} {Number(x.committed_amount).toFixed(2)}</p></div>)}{data.procurement.length===0&&<p className="text-sm text-neutral-500">No purchase commitment recorded.</p>}
      {manager&&<form className="grid gap-2 rounded border bg-neutral-50 p-3 sm:grid-cols-2" onSubmit={(e)=>{e.preventDefault();void submit("procurement",Object.fromEntries(new FormData(e.currentTarget)));}}><input name="purchase_reference" required placeholder="PO / commitment reference" className="rounded border p-2"/><input name="committed_amount" required type="number" min="0" step="0.01" placeholder="Committed SGD" className="rounded border p-2"/><input name="description" required placeholder="Scope / purpose" className="rounded border p-2 sm:col-span-2"/><select name="status" aria-label="Procurement status" className="rounded border p-2"><option value="proposed">Proposed</option><option value="approved">Approved</option><option value="ordered">Ordered</option><option value="received">Received</option></select><button disabled={busy} className="rounded bg-emerald-700 p-2 font-bold text-white">Record commitment</button></form>}</div>
    </div>}
  </section>;
}
