import { NextResponse } from "next/server";
import { getCurrentIdentity } from "@/lib/auth";
import { validateRosterPayload } from "@/lib/incidents/roster";
import { createClient } from "@/lib/supabase/server";
import { errorResponse } from "@/lib/work-orders/api";
type Rpc={ok:boolean;code?:string;message?:string;roster?:unknown};
const status=(code?:string)=>code==="ACCESS_DENIED"?403:code==="NOT_FOUND"?404:code==="DUPLICATE_ROSTER"?409:code==="INTERNAL_ERROR"?500:400;
export async function GET(){const identity=await getCurrentIdentity();if(!identity)return errorResponse("AUTHENTICATION_REQUIRED","Authentication is required.",401);if(!["approver","supervisor","administrator"].includes(identity.role))return errorResponse("ACCESS_DENIED","Roster access is not permitted.",403);try{const supabase=await createClient();const [roster,options]=await Promise.all([supabase.rpc("get_emergency_roster"),identity.role==="approver"?Promise.resolve({data:[],error:null}):supabase.rpc("get_emergency_response_options")]);if(roster.error||options.error)return errorResponse("INTERNAL_ERROR","Emergency roster could not be loaded.",500);return NextResponse.json({ok:true,data:roster.data??[],options:options.data??[],read_only:identity.role==="approver"});}catch{return errorResponse("INTERNAL_ERROR","Emergency roster could not be loaded.",500)}}
export async function POST(request:Request){const identity=await getCurrentIdentity();if(!identity)return errorResponse("AUTHENTICATION_REQUIRED","Authentication is required.",401);if(!["supervisor","administrator"].includes(identity.role))return errorResponse("ACCESS_DENIED","Roster management is not permitted.",403);let body:Record<string,unknown>;try{body=await request.json() as Record<string,unknown>}catch{return errorResponse("VALIDATION_ERROR","Request body must be valid JSON.")};const parsed=validateRosterPayload(body);if(!parsed.value)return errorResponse("VALIDATION_ERROR",parsed.error??"Roster values are invalid.");try{const supabase=await createClient();const {data,error}=await supabase.rpc("upsert_emergency_roster",{p_roster_id:null,p_payload:parsed.value});if(error)return errorResponse("INTERNAL_ERROR","Roster entry could not be created.",500);const result=data as Rpc|null;if(!result?.ok)return errorResponse(result?.code??"INTERNAL_ERROR",result?.message??"Roster entry could not be created.",status(result?.code));return NextResponse.json({ok:true,data:result.roster},{status:201})}catch{return errorResponse("INTERNAL_ERROR","Roster entry could not be created.",500)}}
