import { afterEach, describe, expect, test, vi } from "vitest";
import { GET } from "@/app/api/internal/preview-environment-check/route";
import { classifyLegacyRole, classifySupabaseUrl, diagnosePreviewNetwork, PREVIEW_HOSTNAME, PREVIEW_SUPABASE_URL } from "@/lib/preview-environment-identity";

const originalEnvironment = process.env.VERCEL_ENV;
afterEach(() => { if (originalEnvironment === undefined) delete process.env.VERCEL_ENV; else process.env.VERCEL_ENV = originalEnvironment; });
function jwt(role: string) { const encode = (value: object) => Buffer.from(JSON.stringify(value)).toString("base64url"); return `${encode({ alg: "HS256" })}.${encode({ role })}.signature`; }
const resolved = async () => ({});

describe("Preview network connectivity diagnostic", () => {
  test("accepts only the authoritative Preview project reference", () => {
    expect(classifySupabaseUrl("https://pvajuywwwpjlikqjnvgv.supabase.co")).toBe("PREVIEW_MATCH");
    expect(classifySupabaseUrl("https://pvajuywwwypjlikqjnvgv.supabase.co")).toBe("UNRECOGNIZED");
  });
  test("refuses endpoint outside Preview", async () => { process.env.VERCEL_ENV = "production"; expect((await GET()).status).toBe(404); });
  test("hard-stops on Production hostname without networking", async () => { const request=vi.fn(),resolve=vi.fn();const result=await diagnosePreviewNetwork("preview","https://pyapukytcrsuowmgzqzh.supabase.co",jwt("anon"),jwt("service_role"),request,resolve);expect(result?.hostname).toBe("HOSTNAME_MISMATCH");expect(request).not.toHaveBeenCalled();expect(resolve).not.toHaveBeenCalled(); });
  test("resolves only the approved Preview hostname", async () => { const resolve=vi.fn(resolved),request=vi.fn(async()=>({ok:false,status:401}));await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,resolve);expect(resolve).toHaveBeenCalledWith(PREVIEW_HOSTNAME); });
  test("treats any no-key HTTP response as reachable then tests keys", async () => { const request=vi.fn().mockResolvedValueOnce({ok:true,status:200}).mockResolvedValueOnce({ok:false,status:401}).mockResolvedValueOnce({ok:true,status:200}).mockResolvedValueOnce({ok:true,status:200});const result=await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,resolved);expect(result?.previewEndpoint).toBe("PREVIEW_ENDPOINT_REACHABLE");expect(request).toHaveBeenCalledTimes(4);expect(result?.overall).toBe("PREVIEW_IDENTITY_CONFIRMED"); });
  test("does not test keys when Preview endpoint has no response", async () => { const failure=Object.assign(new TypeError("fetch failed"),{cause:{code:"ENOTFOUND",name:"Error"}});const request=vi.fn().mockResolvedValueOnce({ok:true,status:200}).mockRejectedValueOnce(failure);const result=await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,resolved);expect(request).toHaveBeenCalledTimes(2);expect(result?.anonAcceptance).toBe("NOT_TESTED");expect(result?.networkClassification).toBe("DNS_FAILURE"); });
  test("classifies DNS failure", async () => { const request=vi.fn().mockResolvedValueOnce({ok:true,status:200}).mockRejectedValueOnce(new TypeError("fetch failed"));const result=await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,async()=>{throw new Error("dns")});expect(result?.dns).toBe("DNS_NOT_RESOLVED");expect(result?.conclusion).toBe("DNS_FAILURE"); });
  test("classifies general outbound failure", async () => { const failure=Object.assign(new TypeError("fetch failed"),{cause:{code:"UND_ERR_CONNECT_TIMEOUT"}});const request=vi.fn().mockRejectedValue(failure);const result=await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,resolved);expect(result?.generalHttps).toBe("GENERAL_HTTPS_FAILED");expect(result?.conclusion).toBe("VERCEL_OUTBOUND_NETWORK_FAILURE"); });
  test("classifies TLS failure safely", async () => { const failure=Object.assign(new TypeError("fetch failed"),{cause:{code:"CERT_HAS_EXPIRED",name:"Error"}});const request=vi.fn().mockResolvedValueOnce({ok:true,status:200}).mockRejectedValueOnce(failure);const result=await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,resolved);expect(result?.networkClassification).toBe("TLS_FAILURE");expect(result?.conclusion).toBe("TLS_FAILURE"); });
  test("reports accepted and rejected keys by HTTP status", async () => { const request=vi.fn().mockResolvedValueOnce({ok:true,status:200}).mockResolvedValueOnce({ok:false,status:401}).mockResolvedValueOnce({ok:true,status:200}).mockResolvedValueOnce({ok:false,status:401});const result=await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,resolved);expect(result?.anonAcceptance).toBe("ANON_KEY_ACCEPTED");expect(result?.serviceRoleAcceptance).toBe("SERVICE_ROLE_KEY_REJECTED");expect(result?.overall).toBe("BLOCKED"); });
  test("uses no headers before apikey-only key probes", async () => { const calls:Array<{input:string;init:RequestInit}>=[];const request=async(input:string,init:RequestInit)=>{calls.push({input,init});return{ok:true,status:200}};await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,jwt("anon"),jwt("service_role"),request,resolved);expect(calls[0].input).toBe("https://example.com");expect(calls[0].init.headers).toBeUndefined();expect(calls[1].input).toBe(`${PREVIEW_SUPABASE_URL}/auth/v1/settings`);expect(calls[1].init.headers).toBeUndefined();for(const call of calls.slice(2)){expect(Object.keys(call.init.headers as object)).toEqual(["apikey"]);expect(call.init.headers).not.toHaveProperty("Authorization");}expect(calls.map(c=>c.input).join(" ")).not.toContain("pyapukytcrsuowmgzqzh"); });
  test("keeps role decoding informational",()=>{expect(classifyLegacyRole(jwt("anon"),"anon")).toBe("ANON_ROLE_VALID");expect(classifyLegacyRole(jwt("service_role"),"service_role")).toBe("SERVICE_ROLE_VALID")});
  test("returns no keys payloads URLs IPs or stacks", async () => { const anon=jwt("anon"),service=jwt("service_role"),request=vi.fn().mockResolvedValueOnce({ok:true,status:200}).mockResolvedValueOnce({ok:false,status:401}).mockResolvedValue({ok:true,status:200});const result=await diagnosePreviewNetwork("preview",PREVIEW_SUPABASE_URL,anon,service,request,resolved);const output=JSON.stringify(result);expect(output).not.toContain(anon);expect(output).not.toContain(service);expect(output).not.toContain("https://");expect(output).not.toContain("stack"); });
});
