import { existsSync, readFileSync } from "node:fs";
import { describe, expect, test } from "vitest";
import { classifyPmException, comparePmExceptions, recurrenceLabel } from "@/lib/maintenance/presentation";
import { approvedPmPayload, canCancelPm, canManagePm, type PmOccurrence, type PmRequirement } from "@/lib/maintenance/types";

const root=new URL("../",import.meta.url);const read=(path:string)=>readFileSync(new URL(path,root),"utf8");
const requirement:PmRequirement={id:"requirement-id",requirement_number:"PM-2026-000001",state:"active",current_revision_id:"revision-id",asset:{id:"asset-id",asset_tag:"AHU-01",name:"Main AHU",criticality:"critical",lifecycle_status:"active",site:"Central",location:"Roof"},current_revision:{id:"revision-id",revision_number:2,title:"Inspect AHU",scope:"Inspect filters and bearings",maintenance_type:"preventive",interval_value:1,interval_unit:"month",first_due_date:"2026-08-14",lead_time_days:14,default_priority:"high",estimated_hours:2,evidence_guidance:null,instructions:null,procedure_reference:null,effective_date:"2026-01-01"}};
const occurrence:PmOccurrence={id:"occurrence-id",requirement_id:requirement.id,requirement_revision_id:"revision-id",occurrence_number:1,original_due_date:"2026-08-14",current_due_date:"2026-08-14",generation_status:"pending",generation_attempts:0,last_generation_error_code:null,compliance_state:"due",deferral_count:0};

describe("WP-PM-001B Preventive Maintenance operational UX",()=>{
  test("adds the cohesive authenticated PM navigation and core surfaces",()=>{for(const path of["app/maintenance/page.tsx","app/maintenance/new/page.tsx","app/maintenance/[id]/page.tsx","app/maintenance/[id]/revise/page.tsx"])expect(existsSync(new URL(path,root))).toBe(true);expect(read("components/site-header.tsx")).toContain('href="/maintenance"');for(const label of["PM Requirements","Upcoming Maintenance","PM Exceptions"])expect(read("app/maintenance/page.tsx")).toContain(label)});
  test("shows the approved requirements list fields and P0 filters",()=>{const page=read("app/maintenance/page.tsx");for(const value of["requirement_number","asset_tag","current_revision.title","maintenance_type","recurrenceLabel","current_revision.revision_number","responsible_team","criticality","Due exposure"])expect(page).toContain(value)});
  test("provides an authorized create form with server-derived fields suppressed",()=>{const form=read("components/maintenance/requirement-form.tsx");for(const name of["asset_id","title","scope","maintenance_type","interval_value","interval_unit","first_due_date","lead_time_days","default_priority","department_id","responsible_team_id","estimated_hours","instructions","evidence_guidance","procedure_reference"])expect(form).toContain(`name="${name}"`);for(const forbidden of['name="requirement_number"','name="revision_number"','name="actor"','name="created_at"','name="next_due_date"'])expect(form).not.toContain(forbidden)});
  test("allow-lists PM payload and drops client-controlled domain fields",()=>{expect(approvedPmPayload({title:"Safe",scope:"Scope",requirement_number:"PM-X",revision_number:99,actor:"spoof",created_at:"yesterday",next_due_date:"tomorrow"})).toEqual({title:"Safe",scope:"Scope"})});
  test("matches PM mutation visibility to the database role contract",()=>{expect(canManagePm("supervisor")).toBe(true);expect(canManagePm("administrator")).toBe(true);expect(canManagePm("approver")).toBe(false);expect(canManagePm("technician")).toBe(false);expect(canCancelPm("administrator")).toBe(true);expect(canCancelPm("supervisor")).toBe(false);expect(read("app/maintenance/layout.tsx")).toContain('identity.role === "technician"');expect(read("app/maintenance/layout.tsx")).toContain('redirect("/operations")')});
  test("uses only narrow protected RPC routes and no service-role client",()=>{const routes=["app/api/maintenance/requirements/route.ts","app/api/maintenance/requirements/[id]/revise/route.ts","app/api/maintenance/requirements/[id]/activate/route.ts","app/api/maintenance/requirements/[id]/deactivate/route.ts","app/api/maintenance/occurrences/[id]/generate/route.ts","app/api/maintenance/occurrences/[id]/defer/route.ts","app/api/maintenance/occurrences/[id]/cancel/route.ts","app/api/maintenance/process/route.ts"].map(read).join("\n");for(const rpc of["create_pm_requirement","revise_pm_requirement","activate_pm_requirement","deactivate_pm_requirement","generate_pm_work_order","defer_pm_occurrence","cancel_pm_occurrence","materialize_pm_occurrences","process_due_pm_work"])expect(routes).toContain(rpc);expect(routes).not.toContain("createAdminClient");expect(routes).not.toContain('.from("pm_occurrences").update')});
  test("makes revision explicit and preserves historical meaning",()=>{const form=read("components/maintenance/requirement-form.tsx");const detail=read("app/maintenance/[id]/page.tsx");expect(form).toContain("This creates a new revision");expect(form).toContain("Historical occurrences keep");expect(detail).toContain("Each version is immutable");expect(detail).toContain("Revision history")});
  test("distinguishes Draft Active and Inactive without deletion",()=>{const page=read("app/maintenance/page.tsx");const actions=read("components/maintenance/requirement-actions.tsx");for(const state of["draft","active","inactive"])expect(page).toContain(`value="${state}"`);expect(actions).toContain("they are never deleted");expect(actions).not.toContain('method:"DELETE"')});
  test("formats deterministic calendar recurrence",()=>{expect(recurrenceLabel(requirement.current_revision)).toBe("Every month");expect(recurrenceLabel({...requirement.current_revision,interval_value:2,interval_unit:"week"})).toBe("Every 2 weeks")});
  test("orders PM exceptions by the approved hierarchy",()=>{const failed={...occurrence,generation_status:"generation_failed"};const overdue={...occurrence,current_due_date:"2026-08-01",compliance_state:"overdue"};const failedException=classifyPmException(failed,requirement,"2026-08-14")!;const overdueException=classifyPmException(overdue,requirement,"2026-08-14")!;expect(failedException.rank).toBeLessThan(overdueException.rank);expect([{occurrence:overdue,exception:overdueException},{occurrence:failed,exception:failedException}].sort(comparePmExceptions)[0].exception.kind).toBe("generation_failed")});
  test("classifies due-soon critical, generated-unassigned, repeated deferral and lifecycle exceptions",()=>{expect(classifyPmException(occurrence,requirement,"2026-08-10")?.kind).toBe("due_soon_critical");const high={...requirement,asset:{...requirement.asset,criticality:"high"}};expect(classifyPmException({...occurrence,generation_status:"generated",compliance_state:"scheduled",current_due_date:"2026-09-01",work_order:{id:"work",work_order_number:"FW-1",status:"submitted"}},high,"2026-08-10")?.kind).toBe("generated_unassigned");expect(classifyPmException({...occurrence,compliance_state:"scheduled",current_due_date:"2026-09-01",deferral_count:2},high,"2026-08-10")?.kind).toBe("repeatedly_deferred");expect(classifyPmException({...occurrence,compliance_state:"scheduled",current_due_date:"2026-09-01"},{...high,asset:{...high.asset,lifecycle_status:"decommissioned"}},"2026-08-10")?.kind).toBe("decommissioned_asset");expect(classifyPmException({...occurrence,compliance_state:"scheduled",current_due_date:"2026-09-01"},{...high,asset:{...high.asset,lifecycle_status:"out_of_service"}},"2026-08-10")?.kind).toBe("out_of_service_asset")});
  test("presents upcoming occurrence state separately from Work Order execution",()=>{const page=read("app/maintenance/page.tsx");expect(page).toContain("dated maintenance obligation, not an execution status");expect(page).toContain("Open generated Work Order");expect(page).toContain("Generated Work Orders remain operational tasks")});
  test("supports bounded manual materialization, processing and idempotent generation feedback",()=>{const controls=read("components/maintenance/process-controls.tsx");const actions=read("components/maintenance/occurrence-actions.tsx");expect(controls).toContain("max={addDays(singaporeDate(),366)}");expect(controls).toContain("Manual maintenance processing");expect(actions).toContain('result.code==="NO_CHANGE"');expect(actions).toContain("Existing Work Order confirmed");expect(actions).toContain("Retry Work Order generation")});
  test("supports controlled deferral and repeated-deferral prominence",()=>{const actions=read("components/maintenance/occurrence-actions.tsx");expect(actions).toContain("Original history will remain unchanged");expect(actions).toContain("Your form entries have been retained");expect(read("lib/maintenance/presentation.ts")).toContain("Repeatedly deferred")});
  test("uses explicit Administrator-only cancellation without browser dialogs",()=>{const actions=read("components/maintenance/occurrence-actions.tsx");const route=read("app/api/maintenance/occurrences/[id]/cancel/route.ts");expect(actions).toContain("This does not delete history");expect(actions).not.toContain("confirm(");expect(actions).not.toContain("prompt(");expect(route).toContain("canCancelPm")});
  test("adds authoritative PM context to Asset detail",()=>{const detail=read("app/assets/[id]/page.tsx");for(const label of["Preventive Maintenance","Active requirements","Next due","Overdue occurrences","Recorded deferrals","Recent PM Work and compliance"])expect(detail).toContain(label);expect(detail).toContain("not a regulatory compliance claim")});
  test("keeps generated Work Orders single in Operations and links planning views",()=>{const operations=read("components/operations/OperationsWorkspace.tsx");expect(operations).toContain('href="/maintenance?view=upcoming"');expect(operations).toContain('href="/maintenance?view=exceptions"');expect(operations).toContain("Generated PM Work Orders appear once in the Work Queue")});
  test("limits Mission Control to high-value PM exceptions",()=>{const page=read("app/page.tsx");for(const kind of["generation_failed","decommissioned_asset","overdue"])expect(page).toContain(kind);expect(page).not.toContain('exception.kind==="due_soon_critical"');expect(page).not.toContain('exception.kind==="repeatedly_deferred"')});
  test("uses canonical terminology and defensible occurrence outcomes",()=>{const terms=read("lib/product-terminology.ts");for(const label of["generation_failed","completed_on_time","completed_late","out_of_service"])expect(terms).toContain(label);const page=read("app/maintenance/page.tsx");expect(page).not.toContain("compliance percentage");expect(read("app/assets/[id]/page.tsx")).toContain("occurrence-level operational records")});
  test("suppresses raw UUID presentation",()=>{const ui=["app/maintenance/page.tsx","app/maintenance/[id]/page.tsx","components/maintenance/requirement-form.tsx","components/maintenance/occurrence-actions.tsx"].map(read).join("\n");expect(ui).not.toContain("Internal ID");expect(ui).not.toContain("Raw UUID");expect(ui).not.toMatch(/>\{(?:requirement|occurrence|asset|work_order)\.id\}</)});
  test("uses mobile-oriented cards, wrapping and accessible action targets",()=>{const list=read("app/maintenance/page.tsx");const detail=read("app/maintenance/[id]/page.tsx");const form=read("components/maintenance/requirement-form.tsx");expect(list).toContain("lg:grid-cols-2");expect(detail).toContain("break-words");expect(form).toContain("min-h-11");expect(list).not.toContain("overflow-x-auto");expect(detail).not.toContain("overflow-x-auto")});
  test("provides truthful empty unavailable and recoverable-failure states",()=>{const page=read("app/maintenance/page.tsx");expect(page).toContain("temporarily unavailable");expect(page).toContain("No Maintenance Requirements");expect(page).toContain("No PM exceptions");expect(read("components/maintenance/requirement-form.tsx")).toContain("Your entries have been retained")});
  test("contains no automation or remote mutation implementation",()=>{const files=["app/maintenance/page.tsx","components/maintenance/process-controls.tsx","app/api/maintenance/process/route.ts"].map(read).join("\n").toLowerCase();for(const forbidden of["vercel cron","pg_cron","setinterval(","supabase production","createadminclient"])expect(files).not.toContain(forbidden);expect(files).toContain("human-triggered processing only")});
});
