import { afterEach, describe, expect, test, vi } from "vitest";
import { GET } from "@/app/api/internal/preview-environment-check/route";
import { classifyLegacyRole, classifySupabaseUrl, PREVIEW_PROJECT_REF, PREVIEW_SUPABASE_URL, verifyPreviewIdentity } from "@/lib/preview-environment-identity";

const originalEnvironment = process.env.VERCEL_ENV;
afterEach(() => { if (originalEnvironment === undefined) delete process.env.VERCEL_ENV; else process.env.VERCEL_ENV = originalEnvironment; });
function jwt(role: string) { const encode = (value: object) => Buffer.from(JSON.stringify(value)).toString("base64url"); return `${encode({ alg: "HS256", typ: "JWT" })}.${encode({ role })}.signature`; }
const accepted = vi.fn(async () => ({ ok: true, status: 200 }));

describe("Preview API-key acceptance diagnostic", () => {
  test("accepts only the exact Preview URL", () => expect(classifySupabaseUrl(PREVIEW_SUPABASE_URL)).toBe("PREVIEW_MATCH"));
  test("refuses the Production URL before any request", async () => { const request = vi.fn(); const result = await verifyPreviewIdentity("preview", "https://pyapukytcrsuowmgzqzh.supabase.co", jwt("anon"), jwt("service_role"), request); expect(result?.supabaseUrl).toBe("PRODUCTION_UNSAFE"); expect(request).not.toHaveBeenCalled(); });
  test("refuses an unknown URL before any request", async () => { const request = vi.fn(); const result = await verifyPreviewIdentity("preview", "https://example.invalid", jwt("anon"), jwt("service_role"), request); expect(result?.supabaseUrl).toBe("UNRECOGNIZED"); expect(request).not.toHaveBeenCalled(); });
  test("classifies an accepted anon key", async () => expect((await verifyPreviewIdentity("preview", PREVIEW_SUPABASE_URL, jwt("anon"), jwt("service_role"), accepted))!.anonAcceptance).toBe("ANON_KEY_ACCEPTED"));
  test("classifies a rejected anon key with safe HTTP status", async () => { const request = vi.fn(async () => ({ ok: true, status: 200 })); request.mockResolvedValueOnce({ ok: false, status: 401 }); const result=(await verifyPreviewIdentity("preview", PREVIEW_SUPABASE_URL, jwt("anon"), jwt("service_role"), request))!; expect(result.anonAcceptance).toBe("ANON_KEY_REJECTED"); expect(result.anonHttpStatus).toBe(401); expect(result.anonHttpClass).toBe("UNAUTHORIZED"); });
  test("classifies an accepted service-role key", async () => expect((await verifyPreviewIdentity("preview", PREVIEW_SUPABASE_URL, jwt("anon"), jwt("service_role"), accepted))!.serviceRoleAcceptance).toBe("SERVICE_ROLE_KEY_ACCEPTED"));
  test("classifies a rejected service-role key with safe HTTP status", async () => { const request = vi.fn(async () => ({ ok: true, status: 200 })); request.mockResolvedValueOnce({ ok: true, status: 200 }).mockResolvedValueOnce({ ok: false, status: 403 }); const result=(await verifyPreviewIdentity("preview", PREVIEW_SUPABASE_URL, jwt("anon"), jwt("service_role"), request))!; expect(result.serviceRoleAcceptance).toBe("SERVICE_ROLE_KEY_REJECTED"); expect(result.serviceRoleHttpStatus).toBe(403); expect(result.serviceRoleHttpClass).toBe("FORBIDDEN"); });
  test("validates the anon role structurally without requiring ref", () => expect(classifyLegacyRole(jwt("anon"), "anon")).toBe("ANON_ROLE_VALID"));
  test("validates the service role structurally without requiring ref", () => expect(classifyLegacyRole(jwt("service_role"), "service_role")).toBe("SERVICE_ROLE_VALID"));
  test("reports role mismatches", () => { expect(classifyLegacyRole(jwt("service_role"), "anon")).toBe("ANON_ROLE_MISMATCH"); expect(classifyLegacyRole(jwt("anon"), "service_role")).toBe("SERVICE_ROLE_MISMATCH"); });
  test("uses only apikey on the approved Preview Auth settings endpoint", async () => { const calls: Array<{input:string;init:RequestInit}> = []; const request = async (input: string,init:RequestInit) => { calls.push({input,init}); return { ok: true,status:200 }; }; await verifyPreviewIdentity("preview", PREVIEW_SUPABASE_URL, jwt("anon"), jwt("service_role"), request); expect(calls).toHaveLength(2); for (const call of calls){expect(call.input).toBe(`https://${PREVIEW_PROJECT_REF}.supabase.co/auth/v1/settings`);expect(Object.keys(call.init.headers as object)).toEqual(["apikey"]);expect(call.init.headers).not.toHaveProperty("Authorization");} expect(calls.map(call=>call.input).join(" ")).not.toContain("pyapukytcrsuowmgzqzh"); });
  test("refuses endpoint requests outside Vercel Preview", async () => { process.env.VERCEL_ENV = "production"; expect((await GET()).status).toBe(404); });
  test("returns classifications only and no secrets", async () => { const anon = jwt("anon"), service = jwt("service_role"); const result = await verifyPreviewIdentity("preview", PREVIEW_SUPABASE_URL, anon, service, accepted); expect(result).toEqual({ environment: "preview", supabaseUrl: "PREVIEW_MATCH", anonAcceptance: "ANON_KEY_ACCEPTED", anonHttpStatus:200,anonHttpClass:"SUCCESS", anonRole: "ANON_ROLE_VALID", serviceRoleAcceptance: "SERVICE_ROLE_KEY_ACCEPTED",serviceRoleHttpStatus:200,serviceRoleHttpClass:"SUCCESS", serviceRole: "SERVICE_ROLE_VALID",requestImplementation:"REQUEST_IMPLEMENTATION_VALID", overall: "PREVIEW_IDENTITY_CONFIRMED" }); const serialized = JSON.stringify(result); expect(serialized).not.toContain(anon); expect(serialized).not.toContain(service); expect(serialized).not.toContain("https://"); });
});
