import { beforeEach, describe, expect, test, vi } from "vitest";
import { NextRequest } from "next/server";
const mocks = vi.hoisted(() => ({ getCurrentIdentity: vi.fn(), createClient: vi.fn() }));
vi.mock("@/lib/auth", () => ({ getCurrentIdentity: mocks.getCurrentIdentity }));
vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.createClient }));
import { PATCH } from "@/app/api/work-orders/[id]/assignment/route";
const context = { params: Promise.resolve({ id: "22222222-2222-4222-8222-222222222222" }) };
beforeEach(() => { vi.clearAllMocks(); mocks.getCurrentIdentity.mockResolvedValue({ userId: "actor", role: "supervisor" }); });
describe("legacy assignment adapter", () => {
  test("preserves authentication rejection", async () => { mocks.getCurrentIdentity.mockResolvedValue(null); const response = await PATCH(new NextRequest("http://localhost/api/work-orders/id/assignment", { method: "PATCH", body: JSON.stringify({ technician_id: "11111111-1111-4111-8111-111111111111" }) }), context); expect(response.status).toBe(401); expect(await response.json()).toMatchObject({ code: "AUTHENTICATION_REQUIRED" }); });
  test("maps technician assignment to secure RPC", async () => { const rpc = vi.fn().mockResolvedValue({ data: { ok: true, work_order: { status: "assigned" } }, error: null }); mocks.createClient.mockResolvedValue({ rpc }); const technicianId = "11111111-1111-4111-8111-111111111111"; const response = await PATCH(new NextRequest("http://localhost/api/work-orders/id/assignment", { method: "PATCH", body: JSON.stringify({ technician_id: technicianId }) }), context); expect(response.status).toBe(200); expect(rpc).toHaveBeenCalledWith("assign_work_order", { p_work_order_id: "22222222-2222-4222-8222-222222222222", p_assignment_type: "technician", p_assignee_id: technicianId }); });
  test("maps not-found responses from the canonical assignment route", async () => { mocks.createClient.mockResolvedValue({ rpc: vi.fn().mockResolvedValue({ data: { ok: false, code: "NOT_FOUND", message: "Work order not found." }, error: null }) }); const response = await PATCH(new NextRequest("http://localhost/api/work-orders/id/assignment", { method: "PATCH", body: JSON.stringify({ technician_id: "11111111-1111-4111-8111-111111111111" }) }), context); expect(response.status).toBe(404); expect(await response.json()).toMatchObject({ ok: false, code: "NOT_FOUND" }); });
  test("returns successful no-op assignment results without remapping", async () => { mocks.createClient.mockResolvedValue({ rpc: vi.fn().mockResolvedValue({ data: { ok: true, code: "NO_CHANGE", message: "The work order is already assigned to this assignee.", work_order: { status: "assigned" } }, error: null }) }); const response = await PATCH(new NextRequest("http://localhost/api/work-orders/id/assignment", { method: "PATCH", body: JSON.stringify({ technician_id: "11111111-1111-4111-8111-111111111111" }) }), context); expect(response.status).toBe(200); expect(await response.json()).toMatchObject({ ok: true, code: "NO_CHANGE" }); });
  test("rejects invalid identifiers before RPC", async () => { const response = await PATCH(new NextRequest("http://localhost/api/work-orders/id/assignment", { method: "PATCH", body: JSON.stringify({ technician_id: "invalid" }) }), context); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ code: "INVALID_ASSIGNMENT" }); });
  test("maps malformed compatibility payloads to a structured assignment error", async () => { const response = await PATCH(new NextRequest("http://localhost/api/work-orders/id/assignment", { method: "PATCH", body: "{" }), context); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ ok: false, code: "INVALID_ASSIGNMENT" }); });
  test("preserves inactive-reference conflicts", async () => { mocks.createClient.mockResolvedValue({ rpc: vi.fn().mockResolvedValue({ data: { ok: false, code: "INACTIVE_REFERENCE", message: "The selected assignee is unavailable." }, error: null }) }); const response = await PATCH(new NextRequest("http://localhost/api/work-orders/id/assignment", { method: "PATCH", body: JSON.stringify({ technician_id: "11111111-1111-4111-8111-111111111111" }) }), context); expect(response.status).toBe(409); expect(await response.json()).toMatchObject({ code: "INACTIVE_REFERENCE" }); });
});
