import { beforeEach, describe, expect, test, vi } from "vitest";
const mocks = vi.hoisted(() => ({ getCurrentIdentity: vi.fn(), createClient: vi.fn() }));
vi.mock("@/lib/auth", () => ({ getCurrentIdentity: mocks.getCurrentIdentity }));
vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.createClient }));
import { POST } from "@/app/api/work-orders/route";

const identity = { userId: "11111111-1111-4111-8111-111111111111", email: "requester@example.com", displayName: "Requester", department: "Facilities", role: "reviewer" as const };
const request = (body: unknown) => new Request("http://localhost/api/work-orders", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) });

beforeEach(() => { vi.clearAllMocks(); mocks.getCurrentIdentity.mockResolvedValue(identity); });
describe("POST /api/work-orders", () => {
  test("rejects unauthenticated callers", async () => { mocks.getCurrentIdentity.mockResolvedValue(null); const response = await POST(request({ title: "Leak", location: "L1" })); expect(response.status).toBe(401); expect(await response.json()).toMatchObject({ ok: false, code: "AUTHENTICATION_REQUIRED" }); });
  test("rejects malformed JSON", async () => { const response = await POST(new Request("http://localhost/api/work-orders", { method: "POST", headers: { "content-type": "application/json" }, body: "{" })); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ code: "VALIDATION_ERROR", message: "Request body must be valid JSON." }); });
  test("rejects technicians", async () => { mocks.getCurrentIdentity.mockResolvedValue({ ...identity, role: "technician" }); const response = await POST(request({ title: "Leak", location: "L1" })); expect(response.status).toBe(403); expect(await response.json()).toMatchObject({ code: "ACCESS_DENIED" }); });
  test("validates required fields", async () => { const response = await POST(request({ title: "", location: "L1" })); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ code: "VALIDATION_ERROR" }); });
  test("validates predictive ranges", async () => { const response = await POST(request({ title: "Bearing vibration", location: "Plant", source: "predictive", confidence_score: 1.2 })); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ code: "VALIDATION_ERROR" }); });
  test("creates through the atomic RPC", async () => { const rpc = vi.fn().mockResolvedValue({ data: { ok: true, work_order: { id: "order-1", status: "submitted" } }, error: null }); mocks.createClient.mockResolvedValue({ rpc }); const response = await POST(request({ title: " Bearing vibration ", location: " Plant ", source: "predictive", failure_probability: 0.8, submit: true })); expect(response.status).toBe(201); expect(rpc).toHaveBeenCalledWith("create_work_order", { p_payload: expect.objectContaining({ title: "Bearing vibration", location: "Plant", source: "predictive", status: "submitted", failure_probability: 0.8 }) }); expect(await response.json()).toMatchObject({ ok: true, data: { id: "order-1" } }); });
  test("defaults priority to medium", async () => { const rpc = vi.fn().mockResolvedValue({ data: { ok: true, work_order: { id: "order-1" } }, error: null }); mocks.createClient.mockResolvedValue({ rpc }); const response = await POST(request({ title: "Filter change", location: "AHU room" })); expect(response.status).toBe(201); expect(rpc).toHaveBeenCalledWith("create_work_order", { p_payload: expect.objectContaining({ priority: "medium" }) }); });
  test("validates contact numbers without rejecting legacy punctuation", async () => { const rpc = vi.fn().mockResolvedValue({ data: { ok: true, work_order: { id: "order-1" } }, error: null }); mocks.createClient.mockResolvedValue({ rpc }); const response = await POST(request({ title: "Filter change", location: "AHU room", contact_number: "+65 6123-4567 ext. 89" })); expect(response.status).toBe(201); expect(rpc).toHaveBeenCalledWith("create_work_order", { p_payload: expect.objectContaining({ contact_number: "+65 6123-4567 ext. 89" }) }); });
  test("does not expose RPC transport details", async () => { mocks.createClient.mockResolvedValue({ rpc: vi.fn().mockResolvedValue({ data: null, error: { message: "constraint work_orders_secret" } }) }); const response = await POST(request({ title: "Bearing vibration", location: "Plant" })); expect(response.status).toBe(500); expect(await response.json()).toEqual({ ok: false, code: "INTERNAL_ERROR", message: "Unable to create the work order.", error: "Unable to create the work order." }); });
  test("handles unexpected route exceptions without exposing details", async () => { mocks.createClient.mockRejectedValue(new Error("private connection detail")); const response = await POST(request({ title: "Bearing vibration", location: "Plant" })); expect(response.status).toBe(500); expect(await response.json()).toEqual({ ok: false, code: "INTERNAL_ERROR", message: "Unable to create the work order.", error: "Unable to create the work order." }); });
});
