import { beforeEach, describe, expect, test, vi } from "vitest";
import { NextRequest } from "next/server";
const mocks = vi.hoisted(() => ({ getCurrentIdentity: vi.fn(), createClient: vi.fn() }));
vi.mock("@/lib/auth", () => ({ getCurrentIdentity: mocks.getCurrentIdentity }));
vi.mock("@/lib/supabase/server", () => ({ createClient: mocks.createClient }));
import { PATCH } from "@/app/api/work-orders/[id]/status/route";
const context = { params: Promise.resolve({ id: "22222222-2222-4222-8222-222222222222" }) };
beforeEach(() => { vi.clearAllMocks(); mocks.getCurrentIdentity.mockResolvedValue({ userId: "actor", role: "approver" }); });
describe("legacy status adapter", () => {
  test("preserves authentication rejection", async () => { mocks.getCurrentIdentity.mockResolvedValue(null); const request = new NextRequest("http://localhost/api/work-orders/id/status", { method: "PATCH", body: JSON.stringify({ action: "approve" }) }); const response = await PATCH(request, context); expect(response.status).toBe(401); expect(await response.json()).toMatchObject({ code: "AUTHENTICATION_REQUIRED" }); });
  test("maps reject to secure cancellation", async () => { const rpc = vi.fn().mockResolvedValue({ data: { ok: true, work_order: { status: "cancelled" } }, error: null }); mocks.createClient.mockResolvedValue({ rpc }); const request = new NextRequest("http://localhost/api/work-orders/id/status", { method: "PATCH", body: JSON.stringify({ action: "reject", note: "Invalid request" }) }); const response = await PATCH(request, context); expect(response.status).toBe(200); expect(rpc).toHaveBeenCalledWith("transition_work_order", expect.objectContaining({ p_action: "cancel", p_payload: expect.objectContaining({ reason: "Invalid request" }) })); });
  test("maps not-found responses from the canonical transition route", async () => { mocks.createClient.mockResolvedValue({ rpc: vi.fn().mockResolvedValue({ data: { ok: false, code: "NOT_FOUND", message: "Work order not found." }, error: null }) }); const request = new NextRequest("http://localhost/api/work-orders/id/status", { method: "PATCH", body: JSON.stringify({ action: "approve" }) }); const response = await PATCH(request, context); expect(response.status).toBe(404); expect(await response.json()).toMatchObject({ ok: false, code: "NOT_FOUND" }); });
  test("returns stable invalid-action errors", async () => { const request = new NextRequest("http://localhost/api/work-orders/id/status", { method: "PATCH", body: JSON.stringify({ action: "archive" }) }); const response = await PATCH(request, context); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ code: "VALIDATION_ERROR" }); });
  test("maps malformed compatibility payloads to a structured validation error", async () => { const request = new NextRequest("http://localhost/api/work-orders/id/status", { method: "PATCH", body: "{" }); const response = await PATCH(request, context); expect(response.status).toBe(400); expect(await response.json()).toMatchObject({ ok: false, code: "VALIDATION_ERROR" }); });
  test("preserves structured conflict codes", async () => { mocks.createClient.mockResolvedValue({ rpc: vi.fn().mockResolvedValue({ data: { ok: false, code: "INVALID_TRANSITION", message: "Transition denied." }, error: null }) }); const request = new NextRequest("http://localhost/api/work-orders/id/status", { method: "PATCH", body: JSON.stringify({ action: "start" }) }); const response = await PATCH(request, context); expect(response.status).toBe(409); expect(await response.json()).toMatchObject({ code: "INVALID_TRANSITION" }); });
});
