"use client";

import Image from "next/image";
import { PointerEvent, useEffect, useMemo, useState } from "react";

type Facility = { id: string; code: string; name: string };
type Area = { id: string; facility_id: string; area_code: string; name: string; level: string | null; drawing_reference: string | null; map_x: number | string | null; map_y: number | string | null };
type Drawing = { code: string; title: string; src: string; width: number; height: number };

export default function FacilityAreaLocationConfiguration() {
  const [facilities, setFacilities] = useState<Facility[]>([]), [areas, setAreas] = useState<Area[]>([]), [drawings, setDrawings] = useState<Drawing[]>([]);
  const [facilityId, setFacilityId] = useState(""), [areaId, setAreaId] = useState(""), [drawingCode, setDrawingCode] = useState("");
  const [point, setPoint] = useState<{ x: number; y: number } | null>(null), [message, setMessage] = useState(""), [error, setError] = useState(""), [saving, setSaving] = useState(false);
  useEffect(() => { void fetch("/api/admin/facility-locations", { cache: "no-store" }).then(async (response) => { const result = await response.json(); if (!response.ok) throw new Error(result.error); setFacilities(result.facilities ?? []); setAreas(result.areas ?? []); setDrawings(result.drawings ?? []); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Locations could not be loaded.")); }, []);
  const filteredAreas = useMemo(() => areas.filter((area) => area.facility_id === facilityId), [areas, facilityId]);
  const selectedArea = areas.find((area) => area.id === areaId), selectedDrawing = drawings.find((drawing) => drawing.code === drawingCode);
  function selectArea(id: string) { setAreaId(id); const area = areas.find((candidate) => candidate.id === id); setDrawingCode(area?.drawing_reference ?? ""); const x = Number(area?.map_x), y = Number(area?.map_y); setPoint(area?.map_x !== null && area?.map_y !== null && Number.isFinite(x) && Number.isFinite(y) ? { x, y } : null); setMessage(""); }
  function place(event: PointerEvent<HTMLButtonElement>) { const rect = event.currentTarget.getBoundingClientRect(); setPoint({ x: Math.max(0, Math.min(100, ((event.clientX - rect.left) / rect.width) * 100)), y: Math.max(0, Math.min(100, ((event.clientY - rect.top) / rect.height) * 100)) }); setMessage(""); }
  async function save() { if (!facilityId || !areaId || !drawingCode || !point) return setError("Select a facility, area, drawing and verified point."); setSaving(true); setError(""); setMessage(""); try { const response = await fetch("/api/admin/facility-locations", { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ facility_id: facilityId, facility_area_id: areaId, drawing_reference: drawingCode, map_x: point.x, map_y: point.y }) }); const result = await response.json(); if (!response.ok) throw new Error(result.error); setAreas((current) => current.map((area) => area.id === areaId ? result.area : area)); setMessage("Facility drawing location saved and audited."); } catch (reason) { setError(reason instanceof Error ? reason.message : "Location could not be saved."); } finally { setSaving(false); } }
  return <section className="space-y-5 rounded-xl border border-slate-200 bg-white p-5 shadow-sm"><div className="grid gap-4 md:grid-cols-3"><label className="text-sm font-medium">Facility<select aria-label="Facility" className="mt-1 w-full rounded-lg border p-2" value={facilityId} onChange={(event) => { setFacilityId(event.target.value); setAreaId(""); setPoint(null); }}><option value="">Select facility</option>{facilities.map((facility) => <option key={facility.id} value={facility.id}>{facility.code} · {facility.name}</option>)}</select></label><label className="text-sm font-medium">Facility area<select aria-label="Facility area" className="mt-1 w-full rounded-lg border p-2" value={areaId} onChange={(event) => selectArea(event.target.value)}><option value="">Select area</option>{filteredAreas.map((area) => <option key={area.id} value={area.id}>{area.area_code} · {area.name}</option>)}</select></label><label className="text-sm font-medium">Drawing<select aria-label="Drawing" className="mt-1 w-full rounded-lg border p-2" value={drawingCode} onChange={(event) => { setDrawingCode(event.target.value); setPoint(null); }}><option value="">Select drawing</option>{drawings.map((drawing) => <option key={drawing.code} value={drawing.code}>{drawing.code} · {drawing.title}</option>)}</select></label></div>
    {selectedDrawing && <div><p className="mb-2 text-sm text-slate-600">Click or tap the verified area position on {selectedDrawing.code}. No default point is supplied.</p><button type="button" aria-label={`Place ${selectedArea?.area_code ?? "facility area"} on ${selectedDrawing.code}`} onPointerDown={place} className="relative block w-full overflow-hidden rounded-xl border-2 border-slate-300 bg-slate-100" style={{ aspectRatio: `${selectedDrawing.width}/${selectedDrawing.height}` }}><Image src={selectedDrawing.src} alt={selectedDrawing.title} fill sizes="100vw" className="object-contain" priority />{point && <span aria-label={`Marker preview at ${point.x.toFixed(2)}, ${point.y.toFixed(2)}`} className="pointer-events-none absolute z-10 -translate-x-1/2 -translate-y-1/2 rounded-full border-4 border-white bg-red-600 px-2 py-1 text-sm font-black text-white shadow-xl" style={{ left: `${point.x}%`, top: `${point.y}%` }}>!</span>}</button></div>}
    {point && <p className="text-sm font-semibold text-slate-700">Normalized position: X {point.x.toFixed(2)}% · Y {point.y.toFixed(2)}%</p>}<button type="button" disabled={saving || !point} onClick={() => void save()} className="rounded-lg bg-blue-700 px-4 py-2 font-semibold text-white disabled:opacity-50">{saving ? "Saving…" : "Save verified position"}</button>{message && <p role="status" className="rounded-lg bg-green-50 p-3 text-sm text-green-800">{message}</p>}{error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-800">{error}</p>}</section>;
}
