"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";

export default function CorrectiveWorkOrderForm({ incidentId, location }: { incidentId: string; location: string }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function submit(formData: FormData) { if (busy) return; setBusy(true); setMessage(""); try { const response = await fetch(`/api/incidents/${incidentId}/work-orders`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ title: formData.get("title"), description: formData.get("description"), location, priority: formData.get("priority"), submit: true }) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message || "Corrective work order could not be created."); setMessage("Corrective work order created and linked."); setOpen(false); router.refresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Corrective work order could not be created."); } finally { setBusy(false); } }
  if (!open) return <div><button type="button" onClick={() => setOpen(true)} className="min-h-12 rounded-xl bg-blue-700 px-5 py-3 font-bold text-white focus-visible:outline-none focus-visible:ring-4 focus-visible:ring-blue-300">Create Corrective Work Order</button>{message && <p role="status" className="mt-3 text-sm font-semibold text-emerald-700">{message}</p>}</div>;
  return <form action={submit} className="mt-4 space-y-4 rounded-xl border bg-slate-50 p-4"><label className="block text-sm font-semibold">Title<input name="title" required maxLength={200} className="mt-1 min-h-12 w-full rounded-lg border bg-white px-3" /></label><label className="block text-sm font-semibold">Description<textarea name="description" rows={3} className="mt-1 w-full rounded-lg border bg-white p-3" /></label><label className="block text-sm font-semibold">Priority<select name="priority" defaultValue="high" className="mt-1 min-h-12 w-full rounded-lg border bg-white px-3"><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label>{message && <p role="alert" className="text-sm font-semibold text-red-700">{message}</p>}<div className="flex gap-2"><button disabled={busy} className="min-h-12 rounded-lg bg-blue-700 px-5 font-bold text-white disabled:opacity-50">{busy ? "Creating…" : "Create and link"}</button><button type="button" onClick={() => setOpen(false)} className="min-h-12 rounded-lg border px-5 font-bold">Cancel</button></div></form>;
}
