"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { ASSET_CRITICALITIES, type AssetSystemSummary } from "@/lib/assets/types";

type Option = { id: string; name: string; code?: string };
export default function AssetForm({ systems, departments, teams }: { systems: AssetSystemSummary[]; departments: Option[]; teams: Option[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const input = "mt-1 w-full rounded-lg border border-slate-300 px-3 py-2 text-sm";
  async function submit(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError("");
    try { const response = await fetch("/api/assets", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(new FormData(event.currentTarget))) }); const result = await response.json() as { ok?: boolean; data?: { id?: string }; message?: string }; if (!response.ok || !result.ok || !result.data?.id) throw new Error(result.message ?? "Asset could not be created."); router.push(`/assets/${result.data.id}`); router.refresh(); }
    catch (cause) { setError(cause instanceof Error ? cause.message : "Asset could not be created."); setBusy(false); }
  }
  return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
    {error && <p role="alert" className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    <section><h2 className="font-bold text-slate-950">Identity and consequence</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Asset tag *<input required name="asset_tag" maxLength={100} placeholder="AHU-L03-001" className={input} /></label><label className="text-sm font-medium">Asset name *<input required name="name" maxLength={200} className={input} /></label><label className="text-sm font-medium">Asset type *<input required name="asset_type" maxLength={100} placeholder="Air handling unit" className={input} /></label><label className="text-sm font-medium">Criticality<select name="criticality" defaultValue="medium" className={input}>{ASSET_CRITICALITIES.map((item) => <option key={item} value={item}>{item[0].toUpperCase() + item.slice(1)}</option>)}</select></label><label className="text-sm font-medium">Lifecycle status<select name="lifecycle_status" defaultValue="active" className={input}><option value="active">Active</option><option value="out_of_service">Out of service</option></select></label><label className="text-sm font-medium">System<select name="system_id" className={input}><option value="">Not recorded</option>{systems.filter((item) => item.is_active).map((item) => <option key={item.id} value={item.id}>{item.system_code} · {item.name}</option>)}</select></label></div></section>
    <section><h2 className="font-bold text-slate-950">Location</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Site *<input required name="site" className={input} /></label><label className="text-sm font-medium">Exact location *<input required name="location" className={input} /></label><label className="text-sm font-medium">Building<input name="building" className={input} /></label><label className="text-sm font-medium">Floor / zone<input name="floor_zone" className={input} /></label><label className="text-sm font-medium">Room<input name="room" className={input} /></label></div></section>
    <section><h2 className="font-bold text-slate-950">Equipment and responsibility</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-medium">Manufacturer<input name="manufacturer" className={input} /></label><label className="text-sm font-medium">Model<input name="model" className={input} /></label><label className="text-sm font-medium">Serial number<input name="serial_number" className={input} /></label><label className="text-sm font-medium">Department<select name="department_id" className={input}><option value="">Not recorded</option>{departments.map((item) => <option key={item.id} value={item.id}>{item.code ? `${item.code} · ` : ""}{item.name}</option>)}</select></label><label className="text-sm font-medium">Responsible team<select name="responsible_team_id" className={input}><option value="">Not recorded</option>{teams.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="text-sm font-medium">In-service date<input type="date" name="in_service_date" className={input} /></label><label className="text-sm font-medium">Warranty expiry<input type="date" name="warranty_expiry" className={input} /></label></div><label className="mt-4 block text-sm font-medium">Description<textarea name="description" rows={3} className={input} /></label></section>
    <button disabled={busy} className="min-h-11 rounded-lg bg-blue-700 px-5 py-2.5 font-bold text-white disabled:opacity-50">{busy ? "Creating Asset…" : "Create Asset"}</button>
  </form>;
}
