"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AssetSystemSummary } from "@/lib/assets/types";

export default function AssetSystemManager({ systems }: { systems: AssetSystemSummary[] }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function create(formData: FormData) { setBusy(true); setMessage(""); try { const response = await fetch("/api/assets/systems", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(Object.fromEntries(formData)) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message ?? "Asset System could not be created."); setMessage("Asset System created."); router.refresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Asset System could not be created."); } finally { setBusy(false); } }
  return <details className="rounded-xl border border-slate-200 bg-white p-5"><summary className="cursor-pointer font-black text-slate-950">Asset System configuration <span className="ml-2 text-xs font-normal text-slate-500">Administrator only</span></summary><p className="mt-2 text-sm text-slate-600">Systems are governed functional references and remain separate from physical Assets. Parent hierarchy is not included.</p>{message && <p role="status" className="mt-3 rounded-lg bg-slate-50 p-2 text-sm">{message}</p>}<div className="mt-4 grid gap-5 lg:grid-cols-2"><form action={create} className="grid gap-3"><label className="text-sm font-bold">System code<input required name="system_code" className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-bold">Name<input required name="name" className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-bold">Site<input required name="site" className="mt-1 w-full rounded-lg border p-2" /></label><label className="text-sm font-bold">Description<textarea name="description" rows={2} className="mt-1 w-full rounded-lg border p-2" /></label><button disabled={busy} className="min-h-11 rounded-lg bg-slate-900 px-4 font-bold text-white disabled:opacity-50">{busy ? "Creating…" : "Create Asset System"}</button></form><div><h3 className="text-sm font-black uppercase tracking-wide text-slate-500">Current Systems</h3>{systems.length ? <ul className="mt-2 divide-y divide-slate-100">{systems.map((item) => <li key={item.id} className="flex justify-between gap-3 py-2 text-sm"><span><strong>{item.system_code}</strong> · {item.name}</span><span className={item.is_active ? "text-emerald-700" : "text-slate-400"}>{item.is_active ? "Active" : "Inactive"}</span></li>)}</ul> : <p className="mt-2 text-sm text-slate-500">No Asset Systems recorded.</p>}</div></div></details>;
}
