"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { AssetCriticality, AssetLifecycleStatus } from "@/lib/assets/types";

export default function AssetActions({ assetId, criticality, status, administrator }: { assetId: string; criticality: AssetCriticality; status: AssetLifecycleStatus; administrator: boolean }) {
  const router = useRouter(); const [busy, setBusy] = useState(false); const [message, setMessage] = useState("");
  async function act(endpoint: string, body: Record<string, string>) { setBusy(true); setMessage(""); try { const response = await fetch(`/api/assets/${assetId}/${endpoint}`, { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { message?: string }; if (!response.ok) throw new Error(result.message ?? "Asset update failed."); setMessage("Asset record updated."); router.refresh(); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Asset update failed."); } finally { setBusy(false); } }
  return <section className="rounded-xl border border-amber-200 bg-amber-50 p-5"><h2 className="font-bold text-amber-950">Governed Asset controls</h2><p className="mt-1 text-sm text-amber-800">Lifecycle and criticality describe the master record. They do not imply live equipment health.</p>{message && <p role="status" className="mt-3 rounded bg-white/70 p-2 text-sm">{message}</p>}<div className="mt-4 grid gap-4 lg:grid-cols-2">
    <form action={(form) => act("criticality", { criticality: String(form.get("criticality")), reason: String(form.get("reason")) })} className="space-y-2"><label className="text-sm font-bold">Change criticality<select name="criticality" defaultValue={criticality} className="mt-1 w-full rounded-lg border p-2"><option value="critical">Critical</option><option value="high">High</option><option value="medium">Medium</option><option value="low">Low</option></select></label><input required name="reason" placeholder="Reason required" className="w-full rounded-lg border p-2 text-sm" /><button disabled={busy} className="min-h-11 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white">Apply criticality</button></form>
    <form action={(form) => act("status", { status: String(form.get("status")), reason: String(form.get("reason")) })} className="space-y-2"><label className="text-sm font-bold">Change lifecycle status<select name="status" defaultValue={status} className="mt-1 w-full rounded-lg border p-2"><option value="active">Active</option><option value="out_of_service">Out of service</option>{administrator && <option value="decommissioned">Decommissioned</option>}</select></label><input required name="reason" placeholder="Reason required" className="w-full rounded-lg border p-2 text-sm" /><button disabled={busy || status === "decommissioned"} className="min-h-11 rounded-lg bg-slate-900 px-4 py-2 text-sm font-bold text-white disabled:opacity-50">Apply lifecycle status</button></form>
  </div>{administrator && <form action={(form) => act("tag", { asset_tag: String(form.get("asset_tag")), reason: String(form.get("reason")) })} className="mt-4 grid gap-2 border-t border-amber-200 pt-4 sm:grid-cols-[1fr_2fr_auto]"><input required name="asset_tag" placeholder="Corrected Asset tag" className="rounded-lg border p-2 text-sm" /><input required name="reason" placeholder="Correction reason required" className="rounded-lg border p-2 text-sm" /><button disabled={busy} className="min-h-11 rounded-lg border border-slate-900 px-4 text-sm font-bold">Correct tag</button></form>}</section>;
}
