\set ON_ERROR_STOP on
create or replace function pg_temp.assert_true(c boolean,m text)returns void language plpgsql as $$begin if not coalesce(c,false)then raise exception 'ASSERTION FAILED: %',m;end if;end$$;
insert into auth.users(id,email,raw_user_meta_data)values('27000000-0000-4000-8000-000000000001','doc-admin@example.test','{"display_name":"Document Administrator"}'),('27000000-0000-4000-8000-000000000002','doc-tech@example.test','{"display_name":"Document Technician"}');set fmworks.profile_admin_rpc='on';update public.profiles set role=case when id='27000000-0000-4000-8000-000000000001' then 'administrator' else 'technician' end,is_active=true,deleted_at=null,password_change_required=false where id in('27000000-0000-4000-8000-000000000001','27000000-0000-4000-8000-000000000002');reset fmworks.profile_admin_rpc;
set role authenticated;select set_config('request.jwt.claim.sub','27000000-0000-4000-8000-000000000001',false);
select public.create_sla_document(jsonb_build_object('title','Synthetic Pilot SLA','maintenance_model','HYBRID','agreement_reference','SYN-010','version_label','1','original_filename','pilot.txt','media_type','text/plain','byte_size',20,'content_sha256',repeat('a',64),'storage_key','pilot-db://sql-test','extracted_text','P1 attendance within 30 minutes'))as document \gset
select pg_temp.assert_true((:'document'::jsonb)->>'ok'='true','authorized document ingestion succeeds');select (:'document'::jsonb)->'document'->>'id' as document_id \gset
select public.record_sla_extraction(:'document_id','mock','deterministic-v1',jsonb_build_array(jsonb_build_object('sourceClause','4.2','sourceExcerpt','P1 attendance within 30 minutes','extractedObligation','Attend P1 within 30 minutes','proposedRule',jsonb_build_object('priorityClass','P1','workOrderPriority','critical','serviceCategoryCode','GENERAL','attendanceMinutes',30,'rectificationMinutes',240,'kpiTargetPercent',95),'confidence',.6,'ambiguityWarning','Verify make-safe definition')))as extraction \gset
select pg_temp.assert_true((:'extraction'::jsonb)->>'human_approval_required'='true' and not exists(select 1 from public.sla_extraction_proposals where document_id=:'document_id' and approved_rule_id is not null),'extraction remains non-operational');select id as proposal_id from public.sla_extraction_proposals where document_id=:'document_id' \gset
select public.review_sla_extraction(:'proposal_id','approved_for_draft',jsonb_build_object('attendanceMinutes',25))as reviewed \gset
select pg_temp.assert_true((:'reviewed'::jsonb)->>'ok'='true' and (select proposed_rule->>'attendanceMinutes'='25' and jsonb_array_length(modifications)=1 from public.sla_extraction_proposals where id=:'proposal_id'),'review edit is traceable');
reset role;insert into public.sla_agreements(id,agreement_code,name,created_by)values('27000000-0000-4000-8000-000000000010','SYN-010','Synthetic governed agreement','27000000-0000-4000-8000-000000000001');insert into public.sla_agreement_versions(id,agreement_id,version_number,effective_from,source_reference,approval_status,created_by)values('27000000-0000-4000-8000-000000000011','27000000-0000-4000-8000-000000000010',1,current_date,'Synthetic document FMW-010','pending_approval','27000000-0000-4000-8000-000000000001');set role authenticated;select set_config('request.jwt.claim.sub','27000000-0000-4000-8000-000000000001',false);
select public.approve_reviewed_sla_clause(:'proposal_id','27000000-0000-4000-8000-000000000011')as clause \gset
select pg_temp.assert_true((:'clause'::jsonb)->>'ok'='true' and exists(select 1 from public.sla_extraction_proposals p join public.sla_rules r on r.id=p.approved_rule_id where p.id=:'proposal_id' and p.document_id=:'document_id' and p.source_clause=r.source_clause and r.attendance_minutes=25),'approved rule retains modified proposal and document lineage');
select public.approve_sla_version('27000000-0000-4000-8000-000000000011','Human approval after source review')as activated \gset
select pg_temp.assert_true((:'activated'::jsonb)->>'ok'='true','authorized human approval activates reviewed rule set');
select public.create_staffing_assessment(jsonb_build_object('name','Synthetic hybrid assessment','operating_model','HYBRID','facility_inputs',jsonb_build_object('operating_hours','UNKNOWN'),'proposed_organization','[]'::jsonb))as staffing \gset
select pg_temp.assert_true((:'staffing'::jsonb)->>'ok'='true','hybrid staffing assessment persists');reset role;
set role authenticated;select set_config('request.jwt.claim.sub','27000000-0000-4000-8000-000000000002',false);select pg_temp.assert_true((select count(*)=0 from public.sla_documents)and(select count(*)=0 from public.staffing_assessments),'Technician cannot read contracts or staffing assessments');select pg_temp.assert_true(((public.review_sla_extraction(:'proposal_id','rejected','{}'))::jsonb)->>'code'='ACCESS_DENIED','Technician cannot approve extraction');reset role;
select pg_temp.assert_true(exists(select 1 from public.activity_logs where action='sla_document_ingested')and exists(select 1 from public.activity_logs where action='sla_document_extracted')and exists(select 1 from public.activity_logs where action='sla_extraction_reviewed')and exists(select 1 from public.activity_logs where action='sla_clause_approved')and exists(select 1 from public.activity_logs where action='staffing_assessment_created'),'security-relevant actions are audited');
