"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import type { PmAsset, PmRevision } from "@/lib/maintenance/types";

type Option={id:string;name:string;code?:string};
export default function RequirementForm({assets,departments,teams,requirementId,initial}:{assets:PmAsset[];departments:Option[];teams:Option[];requirementId?:string;initial?:PmRevision}){
  const router=useRouter();const[busy,setBusy]=useState(false);const[error,setError]=useState("");const input="mt-1 min-h-11 w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm focus:border-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-200";const revising=Boolean(requirementId);
  async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setError("");const form=event.currentTarget;const payload=Object.fromEntries(new FormData(form));try{const response=await fetch(revising?`/api/maintenance/requirements/${requirementId}/revise`:"/api/maintenance/requirements",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});const result=await response.json() as{ok?:boolean;data?:{id?:string};requirement?:{id?:string};message?:string};if(!response.ok||!result.ok)throw new Error(result.message??"The Maintenance Requirement could not be saved.");const id=requirementId??result.data?.id??result.requirement?.id;if(!id)throw new Error("The saved requirement could not be opened.");router.push(`/maintenance/${id}`);router.refresh()}catch(cause){setError(cause instanceof Error?cause.message:"The Maintenance Requirement could not be saved.");setBusy(false)}}
  return <form onSubmit={submit} className="space-y-6 rounded-2xl border border-slate-200 bg-white p-5 shadow-sm sm:p-7">
    {error&&<p role="alert" className="rounded-lg border border-red-200 bg-red-50 p-3 text-sm text-red-800">{error} Your entries have been retained.</p>}
    {revising&&<div className="rounded-lg border border-blue-200 bg-blue-50 p-4 text-sm text-blue-900"><strong>This creates a new revision.</strong> Historical occurrences keep the specification revision from which they were generated.</div>}
    <section><h2 className="font-black text-slate-950">Maintenance scope</h2><div className="mt-4 grid gap-4 sm:grid-cols-2">
      {!revising&&<label className="text-sm font-bold sm:col-span-2">Asset *<select required name="asset_id" className={input}><option value="">Select a maintainable Asset</option>{assets.filter(a=>a.lifecycle_status!=="decommissioned").map(a=><option key={a.id} value={a.id}>{a.asset_tag} · {a.name} · {a.location}</option>)}</select></label>}
      <label className="text-sm font-bold sm:col-span-2">Title *<input required name="title" minLength={3} maxLength={200} defaultValue={initial?.title} className={input}/></label>
      <label className="text-sm font-bold sm:col-span-2">Scope *<textarea required name="scope" minLength={3} maxLength={4000} rows={4} defaultValue={initial?.scope} className={input}/></label>
      <label className="text-sm font-bold">Maintenance type<select name="maintenance_type" defaultValue={initial?.maintenance_type??"preventive"} className={input}><option value="preventive">Preventive</option><option value="inspection">Inspection</option></select></label>
      <label className="text-sm font-bold">Default priority<select name="default_priority" defaultValue={initial?.default_priority??"medium"} className={input}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select></label>
    </div></section>
    <section><h2 className="font-black text-slate-950">Calendar recurrence</h2><p className="mt-1 text-sm text-slate-600">Dates are obligations in the FMWorks Singapore business-date policy. The server calculates occurrences.</p><div className="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
      <label className="text-sm font-bold">Every *<input required type="number" name="interval_value" min={1} max={365} defaultValue={initial?.interval_value??1} className={input}/></label>
      <label className="text-sm font-bold">Unit *<select name="interval_unit" defaultValue={initial?.interval_unit??"month"} className={input}><option value="day">Day</option><option value="week">Week</option><option value="month">Month</option><option value="year">Year</option></select></label>
      <label className="text-sm font-bold">Effective date *<input required type="date" name="effective_date" defaultValue={initial?.effective_date} className={input}/></label>
      <label className="text-sm font-bold">First due date *<input required type="date" name="first_due_date" defaultValue={initial?.first_due_date} className={input}/></label>
      <label className="text-sm font-bold">Lead time (days)<input type="number" name="lead_time_days" min={0} max={365} defaultValue={initial?.lead_time_days??0} className={input}/></label>
      <label className="text-sm font-bold">Estimated hours<input type="number" name="estimated_hours" min={0} step="0.25" defaultValue={initial?.estimated_hours??""} className={input}/></label>
      <label className="text-sm font-bold">Department<select name="department_id" defaultValue={initial?.department_id??""} className={input}><option value="">Not recorded</option>{departments.map(o=><option key={o.id} value={o.id}>{o.code?`${o.code} · `:""}{o.name}</option>)}</select></label>
      <label className="text-sm font-bold">Responsible team<select name="responsible_team_id" defaultValue={initial?.responsible_team_id??""} className={input}><option value="">Not recorded</option>{teams.map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label>
    </div></section>
    <section><h2 className="font-black text-slate-950">Execution guidance</h2><div className="mt-4 grid gap-4 sm:grid-cols-2"><label className="text-sm font-bold sm:col-span-2">Instructions<textarea name="instructions" maxLength={4000} rows={3} defaultValue={initial?.instructions??""} className={input}/></label><label className="text-sm font-bold">Evidence guidance<textarea name="evidence_guidance" maxLength={2000} rows={3} defaultValue={initial?.evidence_guidance??""} className={input}/></label><label className="text-sm font-bold">Procedure / checklist reference<textarea name="procedure_reference" maxLength={500} rows={3} defaultValue={initial?.procedure_reference??""} className={input}/></label></div></section>
    {revising&&<label className="block text-sm font-bold">Reason for revision *<textarea required name="revision_reason" minLength={3} rows={3} className={input} aria-describedby="revision-help"/><span id="revision-help" className="mt-1 block font-normal text-slate-500">This reason is written to the audit history.</span></label>}
    <button disabled={busy} className="min-h-11 rounded-lg bg-blue-700 px-5 py-2.5 font-black text-white disabled:opacity-50">{busy?revising?"Creating revision…":"Creating requirement…":revising?"Create new revision":"Create Maintenance Requirement"}</button>
  </form>
}
