import Link from "next/link";
import { redirect } from "next/navigation";
import { getCurrentIdentity } from "@/lib/auth";
import { assetIdentity, assetLocation } from "@/lib/assets/presentation";
import { ASSET_CRITICALITIES, ASSET_LIFECYCLE_STATUSES, canCreateAsset, type AssetSummary, type AssetSystemSummary } from "@/lib/assets/types";
import { operationalLabel } from "@/lib/product-terminology";
import { createClient } from "@/lib/supabase/server";
import AssetSystemManager from "@/components/assets/asset-system-manager";

export const revalidate = 0;
type Search = Promise<Record<string, string | string[] | undefined>>;
const first = (value: string | string[] | undefined) => Array.isArray(value) ? value[0] ?? "" : value ?? "";

export default async function AssetsPage({ searchParams }: { searchParams: Search }) {
  const identity = await getCurrentIdentity(); if (!identity) redirect("/login?next=/assets");
  const params = await searchParams; const search = first(params.search).trim(); const system = first(params.system); const criticality = first(params.criticality); const status = first(params.status); const site = first(params.site).trim(); const type = first(params.type).trim();
  const supabase = await createClient();
  let query = supabase.from("assets").select("id,asset_tag,name,asset_type,criticality,lifecycle_status,site,location,system:asset_systems(name,system_code)");
  const safeSearch = search.replaceAll(/[,%()]/g, " ").trim(); if (safeSearch) query = query.or(`asset_tag.ilike.%${safeSearch}%,name.ilike.%${safeSearch}%,model.ilike.%${safeSearch}%,serial_number.ilike.%${safeSearch}%,location.ilike.%${safeSearch}%`);
  if (system) query = query.eq("system_id", system); if (criticality) query = query.eq("criticality", criticality); if (status) query = query.eq("lifecycle_status", status); if (site) query = query.ilike("site", `%${site}%`); if (type) query = query.ilike("asset_type", `%${type}%`);
  const [assetResult, systemResult] = await Promise.all([query.order("asset_tag").limit(250), supabase.from("asset_systems").select("id,system_code,name,site,is_active").order("system_code")]);
  const assets = (assetResult.error ? [] : assetResult.data ?? []) as unknown as AssetSummary[]; const systems = (systemResult.error ? [] : systemResult.data ?? []) as AssetSystemSummary[];
  return <main className="mx-auto max-w-7xl space-y-6 p-4 sm:p-6 lg:p-8">
    <header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-black uppercase tracking-[.2em] text-blue-700">Maintainable physical equipment</p><h1 className="text-3xl font-black text-slate-950">Asset Registry</h1><p className="mt-2 max-w-2xl text-sm text-slate-600">A shared operational registry for Asset identity, consequence, location, linked work and incidents. Lifecycle status is not live equipment health.</p></div>{canCreateAsset(identity.role) && <Link href="/assets/new" className="min-h-11 rounded-lg bg-blue-700 px-5 py-3 text-sm font-bold text-white">+ Register Asset</Link>}</header>
    <form className="grid gap-3 rounded-xl border border-slate-200 bg-white p-4 sm:grid-cols-2 lg:grid-cols-6"><label className="text-xs font-bold text-slate-600 lg:col-span-2">Search tag, name, model, serial or location<input name="search" defaultValue={search} className="mt-1 w-full rounded-lg border p-2 text-sm" /></label><label className="text-xs font-bold text-slate-600">System<select name="system" defaultValue={system} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="">All systems</option>{systems.map((item) => <option key={item.id} value={item.id}>{item.system_code} · {item.name}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Criticality<select name="criticality" defaultValue={criticality} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="">All criticalities</option>{ASSET_CRITICALITIES.map((item) => <option key={item} value={item}>{operationalLabel(item)}</option>)}</select></label><label className="text-xs font-bold text-slate-600">Lifecycle<select name="status" defaultValue={status} className="mt-1 w-full rounded-lg border p-2 text-sm"><option value="">All visible</option>{ASSET_LIFECYCLE_STATUSES.map((item) => <option key={item} value={item}>{operationalLabel(item)}</option>)}</select></label><div className="flex items-end"><button className="min-h-10 w-full rounded-lg bg-slate-900 px-4 text-sm font-bold text-white">Filter Assets</button></div><label className="text-xs font-bold text-slate-600">Site<input name="site" defaultValue={site} className="mt-1 w-full rounded-lg border p-2 text-sm" /></label><label className="text-xs font-bold text-slate-600">Asset type<input name="type" defaultValue={type} className="mt-1 w-full rounded-lg border p-2 text-sm" /></label></form>
    {assetResult.error ? <div role="alert" className="rounded-xl border border-red-200 bg-red-50 p-5 text-red-800">Asset Registry is temporarily unavailable.</div> : assets.length === 0 ? <div className="rounded-xl border border-dashed border-slate-300 bg-white p-10 text-center"><h2 className="font-black">No Assets match this view</h2><p className="mt-1 text-sm text-slate-500">Adjust the filters or register the first maintainable physical Asset.</p></div> : <ul className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{assets.map((asset) => <li key={asset.id}><Link href={`/assets/${asset.id}`} className="block h-full rounded-xl border border-slate-200 bg-white p-5 shadow-sm transition hover:border-blue-300 hover:shadow"><div className="flex items-start justify-between gap-3"><div><p className="font-mono text-xs font-black text-blue-700">{asset.asset_tag}</p><h2 className="mt-1 text-lg font-black text-slate-950">{asset.name}</h2><p className="text-sm text-slate-500">{asset.asset_type}</p></div><span className={`rounded-full px-2.5 py-1 text-xs font-black ${asset.lifecycle_status === "active" ? "bg-emerald-50 text-emerald-800" : asset.lifecycle_status === "out_of_service" ? "bg-amber-100 text-amber-900" : "bg-slate-200 text-slate-700"}`}>{operationalLabel(asset.lifecycle_status)}</span></div><dl className="mt-4 grid gap-2 text-sm"><div><dt className="text-xs uppercase tracking-wide text-slate-400">System</dt><dd className="font-semibold">{asset.system?.name ?? "Not recorded"}</dd></div><div><dt className="text-xs uppercase tracking-wide text-slate-400">Location</dt><dd>{assetLocation(asset)}</dd></div><div><dt className="text-xs uppercase tracking-wide text-slate-400">Criticality</dt><dd className="font-semibold">{operationalLabel(asset.criticality)}</dd></div></dl><span className="sr-only">Open {assetIdentity(asset)}</span></Link></li>)}</ul>}
    {identity.role === "administrator" && <AssetSystemManager systems={systems} />}
  </main>;
}
